import {
  definePluginAuditEvents,
  definePluginPermissions,
  type PluginDefinition,
} from '@sva/plugin-sdk';
import { studioModuleIamRegistry } from '@sva/studio-module-iam';

import {
  createWasteManagementPluginImportProfiles,
  createWasteManagementPluginJobTypes,
} from './plugin-operations.js';
import { normalizeWasteManagementSearchParams } from './search-params.js';
import { WasteManagementPage } from './waste-management.page.js';

const wasteManagementModuleIam = studioModuleIamRegistry.get('waste-management');

if (!wasteManagementModuleIam) {
  throw new Error('missing_studio_module_iam_contract:waste-management');
}

export const wasteManagementPermissionDefinitions = definePluginPermissions('waste-management', [
  { id: 'waste-management.read', titleKey: 'wasteManagement.permissions.read.title' },
  { id: 'waste-management.master-data.manage', titleKey: 'wasteManagement.permissions.masterDataManage.title' },
  { id: 'waste-management.tours.manage', titleKey: 'wasteManagement.permissions.toursManage.title' },
  { id: 'waste-management.scheduling.manage', titleKey: 'wasteManagement.permissions.schedulingManage.title' },
  { id: 'waste-management.import.execute', titleKey: 'wasteManagement.permissions.importExecute.title' },
  { id: 'waste-management.seed.execute', titleKey: 'wasteManagement.permissions.seedExecute.title' },
  { id: 'waste-management.reset.execute', titleKey: 'wasteManagement.permissions.resetExecute.title' },
  { id: 'waste-management.settings.manage', titleKey: 'wasteManagement.permissions.settingsManage.title' },
]);

export const wasteManagementAuditEventDefinitions = definePluginAuditEvents('waste-management', [
  {
    eventType: 'waste-management.settings.updated',
    titleKey: 'wasteManagement.audit.settingsUpdated',
  },
  {
    eventType: 'waste-management.fraction.created',
    titleKey: 'wasteManagement.audit.fractionCreated',
  },
  {
    eventType: 'waste-management.fraction.updated',
    titleKey: 'wasteManagement.audit.fractionUpdated',
  },
  {
    eventType: 'waste-management.region.created',
    titleKey: 'wasteManagement.audit.regionCreated',
  },
  {
    eventType: 'waste-management.region.updated',
    titleKey: 'wasteManagement.audit.regionUpdated',
  },
  {
    eventType: 'waste-management.city.created',
    titleKey: 'wasteManagement.audit.cityCreated',
  },
  {
    eventType: 'waste-management.city.updated',
    titleKey: 'wasteManagement.audit.cityUpdated',
  },
  {
    eventType: 'waste-management.street.created',
    titleKey: 'wasteManagement.audit.streetCreated',
  },
  {
    eventType: 'waste-management.street.updated',
    titleKey: 'wasteManagement.audit.streetUpdated',
  },
  {
    eventType: 'waste-management.house-number.created',
    titleKey: 'wasteManagement.audit.houseNumberCreated',
  },
  {
    eventType: 'waste-management.house-number.updated',
    titleKey: 'wasteManagement.audit.houseNumberUpdated',
  },
  {
    eventType: 'waste-management.collection-location.created',
    titleKey: 'wasteManagement.audit.collectionLocationCreated',
  },
  {
    eventType: 'waste-management.collection-location.updated',
    titleKey: 'wasteManagement.audit.collectionLocationUpdated',
  },
  {
    eventType: 'waste-management.location-tour-link.created',
    titleKey: 'wasteManagement.audit.locationTourLinkCreated',
  },
  {
    eventType: 'waste-management.location-tour-link.updated',
    titleKey: 'wasteManagement.audit.locationTourLinkUpdated',
  },
  {
    eventType: 'waste-management.location-tour-link.bulk-created',
    titleKey: 'wasteManagement.audit.locationTourLinkBulkCreated',
  },
  {
    eventType: 'waste-management.tour.created',
    titleKey: 'wasteManagement.audit.tourCreated',
  },
  {
    eventType: 'waste-management.tour.updated',
    titleKey: 'wasteManagement.audit.tourUpdated',
  },
  {
    eventType: 'waste-management.tour-date-shift.created',
    titleKey: 'wasteManagement.audit.tourDateShiftCreated',
  },
  {
    eventType: 'waste-management.tour-date-shift.updated',
    titleKey: 'wasteManagement.audit.tourDateShiftUpdated',
  },
  {
    eventType: 'waste-management.global-date-shift.created',
    titleKey: 'wasteManagement.audit.globalDateShiftCreated',
  },
  {
    eventType: 'waste-management.global-date-shift.updated',
    titleKey: 'wasteManagement.audit.globalDateShiftUpdated',
  },
  {
    eventType: 'waste-management.migrations.started',
    titleKey: 'wasteManagement.audit.migrationsStarted',
  },
  {
    eventType: 'waste-management.import.started',
    titleKey: 'wasteManagement.audit.importStarted',
  },
  {
    eventType: 'waste-management.seed.started',
    titleKey: 'wasteManagement.audit.seedStarted',
  },
  {
    eventType: 'waste-management.reset.started',
    titleKey: 'wasteManagement.audit.resetStarted',
  },
  {
    eventType: 'waste-management.data-source.initialized',
    titleKey: 'wasteManagement.audit.dataSourceInitialized',
  },
]);

export const pluginWasteManagement: PluginDefinition = {
  id: 'waste-management',
  displayName: 'Waste Management',
  routes: [
    {
      id: 'waste-management.home',
      path: '/plugins/waste-management',
      guard: 'waste-management.read',
      validateSearch: (search: Record<string, unknown>) => normalizeWasteManagementSearchParams(search),
      component: WasteManagementPage as never,
    },
  ],
  navigation: [
    {
      id: 'waste-management.navigation',
      to: '/plugins/waste-management',
      titleKey: 'wasteManagement.navigation.title',
      section: 'dataManagement',
      requiredAction: 'waste-management.read',
    },
  ],
  permissions: wasteManagementPermissionDefinitions,
  moduleIam: {
    moduleId: wasteManagementModuleIam.moduleId,
    permissionIds: wasteManagementModuleIam.permissionIds,
    systemRoles: wasteManagementModuleIam.systemRoles,
  },
  auditEvents: wasteManagementAuditEventDefinitions,
  jobTypes: createWasteManagementPluginJobTypes(),
  importProfiles: createWasteManagementPluginImportProfiles(),
  translations: {
    de: {
      wasteManagement: {
        navigation: {
          title: 'Abfallkalender',
        },
        page: {
          title: 'Abfallkalender',
          description:
            'Verwalten Sie Stammdaten, Touren, Ausweichtermine und technische Werkzeuge des Waste-Management-Moduls.',
        },
        actions: {
          openSettings: 'Einstellungen öffnen',
        },
        audit: {
          settingsUpdated: 'Waste-Einstellungen aktualisiert',
          fractionCreated: 'Abfallfraktion angelegt',
          fractionUpdated: 'Abfallfraktion aktualisiert',
          regionCreated: 'Region angelegt',
          regionUpdated: 'Region aktualisiert',
          cityCreated: 'Ort angelegt',
          cityUpdated: 'Ort aktualisiert',
          streetCreated: 'Straße angelegt',
          streetUpdated: 'Straße aktualisiert',
          houseNumberCreated: 'Hausnummer angelegt',
          houseNumberUpdated: 'Hausnummer aktualisiert',
          collectionLocationCreated: 'Abholort angelegt',
          collectionLocationUpdated: 'Abholort aktualisiert',
          locationTourLinkCreated: 'Tour-Zuordnung angelegt',
          locationTourLinkUpdated: 'Tour-Zuordnung aktualisiert',
          locationTourLinkBulkCreated: 'Tour-Zuordnungen gesammelt angelegt',
          tourCreated: 'Tour angelegt',
          tourUpdated: 'Tour aktualisiert',
          tourDateShiftCreated: 'Tourbezogenen Ausweichtermin angelegt',
          tourDateShiftUpdated: 'Tourbezogenen Ausweichtermin aktualisiert',
          globalDateShiftCreated: 'Globalen Ausweichtermin angelegt',
          globalDateShiftUpdated: 'Globalen Ausweichtermin aktualisiert',
          migrationsStarted: 'Waste-Migration gestartet',
          importStarted: 'Waste-Import gestartet',
          seedStarted: 'Waste-Seed gestartet',
          resetStarted: 'Waste-Reset gestartet',
          dataSourceInitialized: 'Waste-Datenquelle initialisiert',
        },
        common: {
          yes: 'Ja',
          no: 'Nein',
          active: 'Aktiv',
          inactive: 'Inaktiv',
        },
        filters: {
          searchLabel: 'Suche',
          searchPlaceholder: 'Nach Ort, Straße, Tour oder Abfallart suchen',
          statusLabel: 'Status',
          shiftContextLabel: 'Abweichungskontext',
          status: {
            all: 'Alle Status',
            active: 'Aktiv',
            inactive: 'Inaktiv',
          },
          shiftContext: {
            all: 'Alle Kontexte',
            global: 'Globale Ausweichtermine',
            tour: 'Tourbezogene Ausweichtermine',
          },
        },
        meta: {
          page: 'Seite {{page}}',
          pageSize: '{{pageSize}} Einträge',
          search: 'Suche: {{value}}',
        },
        tabs: {
          ariaLabel: 'Abfallkalender-Bereiche',
          overview: {
            title: 'Überblick',
            body: 'Die zentrale Waste-Historie basiert auf der Studio-Auditspur und macht technische sowie fachliche Mutationen der Instanz sichtbar.',
            emptyTitle: 'Noch keine Waste-Aktivität erfasst',
            emptyBody: 'Sobald Einstellungen, Stammdaten, Touren oder Ausweichtermine geändert werden, erscheint die Historie hier.',
          },
          masterData: {
            title: 'Stammdaten',
            body: 'Hier werden Regionen, Orte, Straßen, Hausnummern, Fraktionen und Abholorte schrittweise angebunden.',
            emptyTitle: 'Stammdaten folgen',
            emptyBody: 'Die Tabellen- und Dialogoberflächen werden in den nächsten Schritten gegen die Host-Fassade angebunden.',
          },
          tours: {
            title: 'Touren',
            body: 'Touren, Zuordnungen und Tour-spezifische Pflege erhalten einen eigenen fachlichen Arbeitsbereich.',
            emptyTitle: 'Touren folgen',
            emptyBody: 'Die erste Route hält bereits den teilbaren Tab- und Filterzustand für diesen Bereich bereit.',
          },
          scheduling: {
            title: 'Ausweichtermine',
            body: 'Globale und tourbezogene Verschiebungen bleiben als eigener Scheduling-Kontext explizit sichtbar.',
            emptyTitle: 'Ausweichtermine folgen',
            emptyBody: 'Hier werden später Kalender-, Bulk- und Konfliktansichten angeschlossen.',
          },
          tools: {
            title: 'Werkzeuge',
            body: 'Import, Migration, Seed und Reset werden über die generische Job-Fähigkeit des Hosts gestartet.',
            emptyTitle: 'Werkzeuge folgen',
            emptyBody: 'Die Job-Starter und Verlaufsanzeigen hängen im nächsten Slice an die Host-Endpunkte.',
          },
          settings: {
            title: 'Einstellungen',
            body: 'Die instanzbezogene Waste-Datenquelle bleibt auch bei Fehlerstatus gezielt erreichbar und rekonfigurierbar.',
            emptyTitle: 'Einstellungen folgen',
            emptyBody: 'Die bestehende Settings-Fassade wird anschließend direkt in diesen Tab integriert.',
          },
        },
        settings: {
          groupTitle: 'Waste-Datenquelle',
          groupDescription: 'Pflegen Sie die instanzbezogene Verbindung zur fachlichen Waste-Datenbank über die Host-Fassade.',
          technical: {
            title: 'Technischer Status',
            description: 'Der Host bewertet die aktive Waste-Datenquelle und spiegelt den letzten serverseitigen Verbindungscheck wider.',
          },
          fields: {
            projectUrl: 'Projekt-URL',
            schemaName: 'Schema',
            databaseUrl: 'Datenbank-URL',
            serviceRoleKey: 'Service-Role-Key',
            enabled: 'Datenquelle aktivieren',
          },
          meta: {
            visibleStatus: 'Status: {{value}}',
            databaseUrlConfigured: 'Datenbank-URL hinterlegt: {{value}}',
            serviceRoleKeyConfigured: 'Service-Key hinterlegt: {{value}}',
            lastCheckedAt: 'Letzter Check: {{value}}',
            databaseUrlConfiguredLabel: 'Datenbank-URL',
            serviceRoleKeyConfiguredLabel: 'Service-Key',
            lastCheckedAtLabel: 'Letzter Check',
          },
          actions: {
            save: 'Einstellungen speichern',
            saving: 'Speichert…',
          },
          messages: {
            loading: 'Einstellungen werden geladen.',
            loadError: 'Die Waste-Einstellungen konnten nicht geladen werden.',
            loadForbidden: 'Für die Waste-Einstellungen fehlt die Berechtigung.',
            saveSuccess: 'Die Waste-Einstellungen wurden gespeichert und serverseitig geprüft.',
            saveError: 'Die Waste-Einstellungen konnten nicht gespeichert werden.',
            saveForbidden: 'Für das Speichern der Waste-Einstellungen fehlt die Berechtigung.',
          },
        },
        overview: {
          messages: {
            loading: 'Waste-Historie wird geladen.',
            loadError: 'Die Waste-Historie konnte nicht geladen werden.',
            loadForbidden: 'Für die Waste-Historie fehlt die Berechtigung.',
            emptyTitle: 'Noch keine Historieneinträge',
            emptyBody: 'Die zentrale Auditspur enthält für diese Suche oder Seite noch keine Waste-Ereignisse.',
          },
          sections: {
            technical: 'Technische Historie',
            audit: 'Audit-Historie',
          },
          meta: {
            total: '{{value}} Historieneinträge gesamt',
            visible: '{{value}} Einträge auf dieser Seite',
            occurredAt: 'Zeitpunkt: {{value}}',
            jobId: 'Job: {{value}}',
            jobTypeId: 'Jobtyp: {{value}}',
            resourceType: 'Ressourcentyp: {{value}}',
            resourceId: 'Ressource: {{value}}',
            reasonCode: 'Reason-Code: {{value}}',
            requestId: 'Request-ID: {{value}}',
          },
          outcome: {
            started: 'Gestartet',
            success: 'Erfolg',
            failure: 'Fehler',
            denied: 'Verweigert',
          },
        },
        masterData: {
          meta: {
            fractionCount: '{{value}} Fraktionen',
            regionCount: '{{value}} Regionen',
            cityCount: '{{value}} Orte',
            streetCount: '{{value}} Straßen',
            houseNumberCount: '{{value}} Hausnummern',
            collectionLocationCount: '{{value}} Abholorte',
          },
          messages: {
            loading: 'Stammdaten werden geladen.',
            loadError: 'Die Waste-Stammdaten konnten nicht geladen werden.',
            loadForbidden: 'Für die Waste-Stammdaten fehlt die Berechtigung.',
            emptyTitle: 'Keine Stammdaten gefunden',
            emptyBody: 'Passen Sie die Filter an oder legen Sie die erste Abfallfraktion an.',
          },
          fractions: {
            title: 'Abfallfraktionen',
            description: 'Pflegen Sie die sichtbaren Fraktionen als ersten echten Mutationspfad des Plugins.',
            color: 'Farbe: {{value}}',
            containerSize: 'Behälter: {{value}}',
            actions: {
              openCreate: 'Fraktion anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Fraktion speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              name: 'Name',
              translationDe: 'Bezeichnung (DE)',
              translationEn: 'Bezeichnung (EN)',
              color: 'Farbe',
              containerSize: 'Behältergröße',
              description: 'Beschreibung',
              active: 'Status',
            },
            translationBadge: '{{locale}}: {{value}}',
            dialog: {
              createTitle: 'Abfallfraktion anlegen',
              createDescription: 'Erstellen Sie eine neue Fraktion für die weitere Touren- und Kalenderpflege.',
              editTitle: 'Abfallfraktion bearbeiten',
              editDescription: 'Ändern Sie Name, Farbe und Sichtbarkeit der Fraktion.',
            },
            messages: {
              createSuccess: 'Die Waste-Fraktion wurde angelegt.',
              updateSuccess: 'Die Waste-Fraktion wurde aktualisiert.',
              saveError: 'Die Waste-Fraktion konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Fraktionen fehlt die Berechtigung.',
            },
          },
          regions: {
            title: 'Regionen',
            description: 'Pflegen Sie Regionen als zweiten kleinen Stammdatenpfad mit eigenem Dialog.',
            regionId: 'Region-ID: {{value}}',
            actions: {
              openCreate: 'Region anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Region speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              name: 'Name',
            },
            dialog: {
              createTitle: 'Region anlegen',
              createDescription: 'Erstellen Sie eine neue Region für die geografische Hierarchie.',
              editTitle: 'Region bearbeiten',
              editDescription: 'Ändern Sie den Namen der Region.',
            },
            messages: {
              createSuccess: 'Die Waste-Region wurde angelegt.',
              updateSuccess: 'Die Waste-Region wurde aktualisiert.',
              saveError: 'Die Waste-Region konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Regionen fehlt die Berechtigung.',
            },
          },
          cities: {
            title: 'Orte',
            description: 'Pflegen Sie Orte mit optionaler Regionszuordnung als ersten relationalen Stammdatenpfad.',
            cityId: 'Ort-ID: {{value}}',
            regionId: 'Region-ID: {{value}}',
            actions: {
              openCreate: 'Ort anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Ort speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              name: 'Name',
              regionId: 'Region',
              regionUnset: 'Keine Region',
            },
            dialog: {
              createTitle: 'Ort anlegen',
              createDescription: 'Erstellen Sie einen Ort und ordnen Sie ihn bei Bedarf einer Region zu.',
              editTitle: 'Ort bearbeiten',
              editDescription: 'Ändern Sie den Namen oder die Regionszuordnung des Orts.',
            },
            messages: {
              createSuccess: 'Der Waste-Ort wurde angelegt.',
              updateSuccess: 'Der Waste-Ort wurde aktualisiert.',
              saveError: 'Der Waste-Ort konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Orten fehlt die Berechtigung.',
            },
          },
          streets: {
            title: 'Straßen',
            description: 'Pflegen Sie Straßen als eigenständigen Adresspfad unterhalb der Orte.',
            streetId: 'Straßen-ID: {{value}}',
            cityId: 'Ort-ID: {{value}}',
            actions: {
              openCreate: 'Straße anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Straße speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              name: 'Name',
              cityId: 'Ort',
              cityUnset: 'Ort auswählen',
            },
            dialog: {
              createTitle: 'Straße anlegen',
              createDescription: 'Erstellen Sie eine Straße und ordnen Sie sie einem Ort zu.',
              editTitle: 'Straße bearbeiten',
              editDescription: 'Ändern Sie den Namen oder den zugeordneten Ort der Straße.',
            },
            messages: {
              createSuccess: 'Die Waste-Straße wurde angelegt.',
              updateSuccess: 'Die Waste-Straße wurde aktualisiert.',
              saveError: 'Die Waste-Straße konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Straßen fehlt die Berechtigung.',
            },
          },
          houseNumbers: {
            title: 'Hausnummern',
            description: 'Pflegen Sie Hausnummern als letzten direkten Pfad der Adresshierarchie.',
            houseNumberId: 'Hausnummer-ID: {{value}}',
            streetId: 'Straßen-ID: {{value}}',
            actions: {
              openCreate: 'Hausnummer anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Hausnummer speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              number: 'Hausnummer',
              streetId: 'Straße',
              streetUnset: 'Straße auswählen',
            },
            dialog: {
              createTitle: 'Hausnummer anlegen',
              createDescription: 'Erstellen Sie eine Hausnummer und ordnen Sie sie einer Straße zu.',
              editTitle: 'Hausnummer bearbeiten',
              editDescription: 'Ändern Sie Hausnummer oder Straßenbezug.',
            },
            messages: {
              createSuccess: 'Die Waste-Hausnummer wurde angelegt.',
              updateSuccess: 'Die Waste-Hausnummer wurde aktualisiert.',
              saveError: 'Die Waste-Hausnummer konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Hausnummern fehlt die Berechtigung.',
            },
          },
          collectionLocations: {
            title: 'Abholorte',
            description: 'Pflegen Sie konkrete Abholorte mit geografischer Auswahl bis auf Hausnummernebene.',
            actions: {
              openCreate: 'Abholort anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Abholort speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              regionId: 'Region',
              regionUnset: 'Alle Regionen',
              cityId: 'Ort',
              cityUnset: 'Ort auswählen',
              streetId: 'Straße',
              streetUnset: 'Alle Straßen',
              houseNumberId: 'Hausnummer',
              houseNumberUnset: 'Alle Hausnummern',
              active: 'Status',
            },
            dialog: {
              createTitle: 'Abholort anlegen',
              createDescription: 'Erstellen Sie einen neuen Abholort aus Region, Ort, Straße und Hausnummer.',
              editTitle: 'Abholort bearbeiten',
              editDescription: 'Ändern Sie geografische Zuordnung und Sichtbarkeit des Abholorts.',
            },
            meta: {
              locationId: 'Abholort-ID: {{value}}',
              allStreets: 'Alle Straßen',
              allHouseNumbers: 'Alle Hausnummern',
            },
            messages: {
              createSuccess: 'Der Waste-Abholort wurde angelegt.',
              updateSuccess: 'Der Waste-Abholort wurde aktualisiert.',
              saveError: 'Der Waste-Abholort konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Abholorten fehlt die Berechtigung.',
            },
            bulk: {
              actions: {
                openAssign: '{{value}} auswählen und Tour zuweisen',
                selectAllFiltered: 'Alle gefilterten Abholorte auswählen',
                cancel: 'Abbrechen',
                assign: 'Tour zuweisen',
                saving: 'Speichert…',
              },
              fields: {
                tourId: 'Tour',
                tourUnset: 'Tour auswählen',
                startDate: 'Startdatum',
                endDate: 'Enddatum',
              },
              dialog: {
                title: 'Tour gesammelt zuweisen',
                description: '{{value}} ausgewählte Abholorte werden einer Tour zugeordnet.',
              },
              selectedTitle: 'Ausgewählte Abholorte',
              meta: {
                selectedCount: '{{value}} ausgewählt',
              },
              messages: {
                assignSuccess: 'Die Waste-Tour-Zuordnungen wurden gesammelt angelegt.',
                assignError: 'Die Waste-Tour-Zuordnungen konnten nicht gesammelt gespeichert werden.',
                assignForbidden: 'Für das Sammelspeichern von Waste-Tour-Zuordnungen fehlt die Berechtigung.',
              },
            },
          },
        },
        tools: {
          imports: {
            title: 'Importe',
            description:
              'Startet fachnahe Waste-Importe als dünne Bedienhülle auf der generischen Host-Job-Fähigkeit.',
            profileLabel: 'Importprofil',
            blobRefLabel: 'Quell-Referenz (Blob-Ref)',
            sourceFormatLabel: 'Quellformat',
            sourceFormats: {
              csv: 'CSV',
              xlsx: 'Excel (.xlsx)',
            },
            dryRunLabel: 'Nur Vorprüfung (Dry-Run)',
            templateColumns: 'Kanonische Importspalten',
          },
          migrations: {
            title: 'Migrationen',
            description: 'Startet asynchrone Host-Migrationsjobs gegen die aktive Waste-Datenquelle.',
            schemaLabel: 'Zielschema',
            versionLabel: 'Anfordernde Version',
          },
          seed: {
            title: 'Seed',
            description: 'Füllt die Waste-Datenquelle über die generische Job-Fähigkeit mit der Baseline.',
          },
          reset: {
            title: 'Reset',
            description: 'Reset bleibt ein hochriskanter Pfad und verlangt ein explizites Bestätigungstoken.',
            tokenLabel: 'Bestätigungstoken',
            confirmTitle: 'Reset wirklich starten?',
            confirmDescription: 'Dieser Reset ist hochriskant. Bestätigen Sie den Vorgang explizit mit dem Token.',
            confirmCancel: 'Abbrechen',
            confirmAction: 'Reset bestätigen',
          },
          actions: {
            startImport: 'Import starten',
            startMigrations: 'Migrationen starten',
            startSeed: 'Seed starten',
            startReset: 'Reset starten',
            starting: 'Startet…',
            downloadTemplate: 'Vorlage laden',
            openJob: 'Job öffnen',
          },
          messages: {
            jobStarted: 'Job {{jobId}} wurde gestartet.',
            jobStartError: 'Der Waste-Job konnte nicht gestartet werden.',
            forbidden: 'Für diese Waste-Operation fehlt die Berechtigung.',
            importValidationError: 'Der Import verlangt ein Importprofil und eine gültige Quell-Referenz.',
            resetValidationError: 'Der Reset verlangt ein gültiges Bestätigungstoken.',
          },
          meta: {
            lastJobTitle: 'Letzter technischer Job',
            lastJobDescription: 'Zuletzt gestarteter Waste-Host-Job mit technischem Status.',
            noJobYet: 'Noch kein technischer Waste-Job gestartet.',
            noJobStatus: 'Kein Job',
            technicalHistoryTitle: 'Technische Ereignisse',
            technicalHistoryDescription:
              'Zeigt die letzten technischen Waste-Ereignisse mit unterscheidbaren Ergebnissen für Start, Erfolg und Fehler.',
            noTechnicalHistory: 'Noch keine technischen Waste-Ereignisse vorhanden.',
            jobId: 'Job: {{value}}',
            jobType: 'Typ: {{value}}',
            jobStatus: 'Status: {{value}}',
            jobIdLabel: 'Job',
            jobTypeLabel: 'Typ',
            jobStatusLabel: 'Status',
          },
        },
        tours: {
          actions: {
            openCreate: 'Tour anlegen',
            edit: 'Bearbeiten',
            cancel: 'Abbrechen',
            create: 'Tour speichern',
            save: 'Änderungen speichern',
            saving: 'Speichert…',
          },
          fields: {
            name: 'Name',
            description: 'Beschreibung',
            recurrence: 'Rhythmus',
            recurrenceUnset: 'Kein Rhythmus',
            firstDate: 'Erster Termin',
            endDate: 'Letzter Termin',
            customDates: 'Individuelle Termine',
            customDatesPlaceholder: '2026-05-12 | Sonderabfuhr\n2026-05-26',
            wasteFractions: 'Abfallfraktionen',
            noFractionsAvailable: 'Es sind noch keine Abfallfraktionen vorhanden.',
            active: 'Status',
          },
          dialog: {
            createTitle: 'Tour anlegen',
            createDescription: 'Erstellen Sie die erste bearbeitbare Tour inklusive Fraktionen und Terminlogik.',
            editTitle: 'Tour bearbeiten',
            editDescription: 'Passen Sie Fraktionen, Rhythmus und Datumslogik der Tour an.',
          },
          meta: {
            count: '{{value}} Touren',
            recurrence: 'Rhythmus: {{value}}',
            fractionCount: 'Fraktionen: {{value}}',
            locationCount: 'Abholorte: {{value}}',
            dateRange: 'Zeitraum: {{value}}',
            tourId: 'Tour-ID: {{value}}',
          },
          recurrence: {
            weekly: 'Wöchentlich',
            biweekly: 'Zweiwöchentlich',
            fourweekly: 'Vierwöchentlich',
            yearly: 'Jährlich',
            onDemand: 'Bedarfsabhängig',
            custom: 'Individuell',
          },
          customDates: {
            title: 'Individuelle Termine',
          },
          assignments: {
            title: 'Zuordnungen',
            actions: {
              openCreate: 'Zuordnung anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Zuordnung speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              tourId: 'Tour',
              tourUnset: 'Tour auswählen',
              locationId: 'Abholort',
              locationUnset: 'Abholort auswählen',
              startDate: 'Startdatum',
              endDate: 'Enddatum',
            },
            dialog: {
              createTitle: 'Tour-Zuordnung anlegen',
              editTitle: 'Tour-Zuordnung bearbeiten',
              description: 'Pflegen Sie Abholorte und optionale Gültigkeitszeiträume für {{value}}.',
              descriptionFallback: 'Pflegen Sie Abholorte und optionale Gültigkeitszeiträume.',
            },
            meta: {
              startDate: 'Start: {{value}}',
              endDate: 'Ende: {{value}}',
            },
            messages: {
              createSuccess: 'Die Waste-Tour-Zuordnung wurde angelegt.',
              updateSuccess: 'Die Waste-Tour-Zuordnung wurde aktualisiert.',
              saveError: 'Die Waste-Tour-Zuordnung konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern von Waste-Tour-Zuordnungen fehlt die Berechtigung.',
            },
          },
          yearCalendar: {
            title: 'Jahreskalender',
            description: 'Zeigt die geplanten Termine für {{value}} inklusive bekannter Verschiebungen.',
            descriptionFallback: 'Zeigt die geplanten Termine inklusive bekannter Verschiebungen.',
            actions: {
              open: 'Jahreskalender',
              previousYear: 'Vorjahr',
              nextYear: 'Folgejahr',
            },
            meta: {
              year: 'Jahr {{value}}',
              dateListTitle: 'Geplante Termine',
              noDates: 'Für dieses Jahr konnten keine Termine berechnet werden.',
            },
          },
          messages: {
            loading: 'Touren werden geladen.',
            loadError: 'Die Waste-Touren konnten nicht geladen werden.',
            loadForbidden: 'Für die Waste-Touren fehlt die Berechtigung.',
            emptyTitle: 'Keine Touren gefunden',
            emptyBody: 'Passen Sie die Filter an oder hinterlegen Sie Touren in der Waste-Datenquelle.',
            createSuccess: 'Die Waste-Tour wurde angelegt.',
            updateSuccess: 'Die Waste-Tour wurde aktualisiert.',
            saveError: 'Die Waste-Tour konnte nicht gespeichert werden.',
            saveForbidden: 'Für das Speichern von Waste-Touren fehlt die Berechtigung.',
          },
        },
        scheduling: {
          global: {
            title: 'Globale Ausweichtermine',
            description: 'Verschiebungen mit globaler Wirkung über mehrere Touren hinweg.',
            cardTitle: 'Globaler Termin {{value}}',
            actions: {
              openCreate: 'Globalen Termin anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Ausweichtermin speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              originalDate: 'Ursprünglicher Termin',
              actualDate: 'Verschobener Termin',
              reasonType: 'Abweichungsgrund',
              reasonTypeUnset: 'Grund auswählen',
              reasonKey: 'Grundschlüssel',
              description: 'Beschreibung',
              hasYear: 'Jahresbezug',
              tourIds: 'Betroffene Touren',
              noToursAvailable: 'Es sind noch keine Touren vorhanden.',
            },
            dialog: {
              createTitle: 'Globalen Ausweichtermin anlegen',
              createDescription: 'Erstellen Sie eine globale Verschiebung mit optional betroffenen Touren.',
              editTitle: 'Globalen Ausweichtermin bearbeiten',
              editDescription: 'Passen Sie Termin, Beschreibung oder betroffene Touren an.',
            },
            messages: {
              createSuccess: 'Der globale Waste-Ausweichtermin wurde angelegt.',
              updateSuccess: 'Der globale Waste-Ausweichtermin wurde aktualisiert.',
              saveError: 'Der globale Waste-Ausweichtermin konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern globaler Waste-Ausweichtermine fehlt die Berechtigung.',
            },
          },
          tour: {
            title: 'Tourbezogene Ausweichtermine',
            description: 'Gezielte Einzelverschiebungen für konkrete Touren.',
            cardTitle: 'Tour {{value}}',
            actions: {
              openCreate: 'Tourtermin anlegen',
              edit: 'Bearbeiten',
              cancel: 'Abbrechen',
              create: 'Ausweichtermin speichern',
              save: 'Änderungen speichern',
              saving: 'Speichert…',
            },
            fields: {
              tourId: 'Tour',
              tourUnset: 'Tour auswählen',
              originalDate: 'Ursprünglicher Termin',
              actualDate: 'Verschobener Termin',
              reasonType: 'Abweichungsgrund',
              reasonTypeUnset: 'Grund auswählen',
              reasonKey: 'Grundschlüssel',
              followUpMode: 'Folgeeffekt',
              followUpModeUnset: 'Kein Folgeeffekt',
              description: 'Beschreibung',
              hasYear: 'Jahresbezug',
            },
            dialog: {
              createTitle: 'Tourbezogenen Ausweichtermin anlegen',
              createDescription: 'Erstellen Sie eine gezielte Einzelverschiebung für eine konkrete Tour.',
              editTitle: 'Tourbezogenen Ausweichtermin bearbeiten',
              editDescription: 'Passen Sie Tour, Termin oder Beschreibung der Einzelverschiebung an.',
            },
            messages: {
              createSuccess: 'Der tourbezogene Waste-Ausweichtermin wurde angelegt.',
              updateSuccess: 'Der tourbezogene Waste-Ausweichtermin wurde aktualisiert.',
              saveError: 'Der tourbezogene Waste-Ausweichtermin konnte nicht gespeichert werden.',
              saveForbidden: 'Für das Speichern tourbezogener Waste-Ausweichtermine fehlt die Berechtigung.',
            },
          },
          meta: {
            globalCount: '{{value}} globale Termine',
            tourCount: '{{value}} tourbezogene Termine',
            hasYear: 'Jahresbezug: {{value}}',
            affectedTours: 'Betroffene Touren: {{value}}',
            reasonType: 'Grund: {{value}}',
            reasonKey: 'Schlüssel: {{value}}',
            followUpMode: 'Folgeeffekt: {{value}}',
          },
          reasonTypes: {
            holiday: 'Feiertag',
            'global-deviation': 'Globale Abweichung',
            'manual-adjustment': 'Manuelle Anpassung',
            'operational-disruption': 'Betriebsstörung',
            weather: 'Wetter',
            other: 'Sonstiges',
          },
          followUpModes: {
            none: 'Keiner',
            'propagate-series': 'Serie fortschreiben',
            'mark-follow-up-dates': 'Folgetermine markieren',
          },
          messages: {
            loading: 'Ausweichtermine werden geladen.',
            loadError: 'Die Waste-Ausweichtermine konnten nicht geladen werden.',
            loadForbidden: 'Für die Waste-Ausweichtermine fehlt die Berechtigung.',
            emptyTitle: 'Keine Ausweichtermine gefunden',
            emptyBody: 'Passen Sie die Filter an oder hinterlegen Sie Ausweichtermine in der Waste-Datenquelle.',
          },
        },
        permissions: {
          read: { title: 'Abfallkalender lesen' },
          masterDataManage: { title: 'Stammdaten verwalten' },
          toursManage: { title: 'Touren verwalten' },
          schedulingManage: { title: 'Ausweichtermine verwalten' },
          importExecute: { title: 'Importe ausführen' },
          seedExecute: { title: 'Seed ausführen' },
          resetExecute: { title: 'Reset ausführen' },
          settingsManage: { title: 'Einstellungen verwalten' },
        },
      },
    },
    en: {
      wasteManagement: {
        navigation: {
          title: 'Waste calendar',
        },
        page: {
          title: 'Waste calendar',
          description: 'Manage master data, tours, schedule deviations and technical tools for waste management.',
        },
        actions: {
          openSettings: 'Open settings',
        },
        common: {
          yes: 'Yes',
          no: 'No',
          active: 'Active',
          inactive: 'Inactive',
        },
        filters: {
          searchLabel: 'Search',
          searchPlaceholder: 'Search by city, street, tour or waste fraction',
          statusLabel: 'Status',
          shiftContextLabel: 'Deviation context',
          status: {
            all: 'All statuses',
            active: 'Active',
            inactive: 'Inactive',
          },
          shiftContext: {
            all: 'All contexts',
            global: 'Global shifts',
            tour: 'Tour shifts',
          },
        },
        meta: {
          page: 'Page {{page}}',
          pageSize: '{{pageSize}} entries',
          search: 'Search: {{value}}',
        },
        tabs: {
          ariaLabel: 'Waste calendar areas',
          overview: {
            title: 'Overview',
            body: 'The main path is now materialized as a free plugin and keeps its reload-stable state through typed search params.',
            emptyTitle: 'Overview coming next',
            emptyBody: 'Upcoming slices add metrics, status surfaces and job hints.',
          },
          masterData: {
            title: 'Master data',
            body: 'Regions, cities, streets, house numbers, fractions and collection locations will be connected here step by step.',
            emptyTitle: 'Master data coming next',
            emptyBody: 'Table and dialog surfaces will be wired to the host facade in the next steps.',
          },
          tours: {
            title: 'Tours',
            body: 'Tours, assignments and tour-specific maintenance get their own focused work area.',
            emptyTitle: 'Tours coming next',
            emptyBody: 'The first route already preserves shareable tab and filter state for this area.',
          },
          scheduling: {
            title: 'Schedule deviations',
            body: 'Global and tour-related shifts remain visible as an explicit scheduling context.',
            emptyTitle: 'Schedule deviations coming next',
            emptyBody: 'Calendar, bulk and conflict surfaces will be added here later.',
          },
          tools: {
            title: 'Tools',
            body: 'Import, migration, seed and reset are started through the host generic job capability.',
            emptyTitle: 'Tools coming next',
            emptyBody: 'Job starters and progress views will be attached to the host endpoints in the next slice.',
          },
          settings: {
            title: 'Settings',
            body: 'The instance-specific waste data source remains reachable and reconfigurable even during error states.',
            emptyTitle: 'Settings coming next',
            emptyBody: 'The existing settings facade will be integrated directly into this tab afterwards.',
          },
        },
        settings: {
          groupTitle: 'Waste data source',
          groupDescription: 'Maintain the instance-specific connection to the waste database through the host facade.',
          technical: {
            title: 'Technical status',
            description: 'The host evaluates the active waste data source and reflects the latest server-side connection check.',
          },
          fields: {
            projectUrl: 'Project URL',
            schemaName: 'Schema',
            databaseUrl: 'Database URL',
            serviceRoleKey: 'Service role key',
            enabled: 'Enable data source',
          },
          meta: {
            visibleStatus: 'Status: {{value}}',
            databaseUrlConfigured: 'Database URL configured: {{value}}',
            serviceRoleKeyConfigured: 'Service key configured: {{value}}',
            lastCheckedAt: 'Last check: {{value}}',
            databaseUrlConfiguredLabel: 'Database URL',
            serviceRoleKeyConfiguredLabel: 'Service key',
            lastCheckedAtLabel: 'Last check',
          },
          actions: {
            save: 'Save settings',
            saving: 'Saving…',
          },
          messages: {
            loading: 'Loading settings.',
            loadError: 'Waste settings could not be loaded.',
            loadForbidden: 'Missing permission to read waste settings.',
            saveSuccess: 'Waste settings were saved and validated server-side.',
            saveError: 'Waste settings could not be saved.',
            saveForbidden: 'Missing permission to save waste settings.',
          },
        },
        overview: {
          messages: {
            loading: 'Loading waste history.',
            loadError: 'Waste history could not be loaded.',
            loadForbidden: 'Missing permission for waste history.',
            emptyTitle: 'No history entries yet',
            emptyBody: 'The central audit trail does not yet contain waste events for this search or page.',
          },
          sections: {
            technical: 'Technical history',
            audit: 'Audit history',
          },
          meta: {
            total: '{{value}} history entries total',
            visible: '{{value}} entries on this page',
            occurredAt: 'Occurred at: {{value}}',
            jobId: 'Job: {{value}}',
            jobTypeId: 'Job type: {{value}}',
            resourceType: 'Resource type: {{value}}',
            resourceId: 'Resource: {{value}}',
            reasonCode: 'Reason code: {{value}}',
            requestId: 'Request ID: {{value}}',
          },
          outcome: {
            started: 'Started',
            success: 'Success',
            failure: 'Failure',
            denied: 'Denied',
          },
        },
        masterData: {
          meta: {
            fractionCount: '{{value}} fractions',
            regionCount: '{{value}} regions',
            cityCount: '{{value}} cities',
            streetCount: '{{value}} streets',
            houseNumberCount: '{{value}} house numbers',
            collectionLocationCount: '{{value}} collection locations',
          },
          messages: {
            loading: 'Loading master data.',
            loadError: 'Waste master data could not be loaded.',
            loadForbidden: 'Missing permission for waste master data.',
            emptyTitle: 'No master data found',
            emptyBody: 'Adjust the filters or create the first waste fraction.',
          },
          fractions: {
            title: 'Waste fractions',
            description: 'Maintain visible fractions as the first real mutation path of the plugin.',
            color: 'Color: {{value}}',
            containerSize: 'Container: {{value}}',
            actions: {
              openCreate: 'Create fraction',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save fraction',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              name: 'Name',
              translationDe: 'Label (DE)',
              translationEn: 'Label (EN)',
              color: 'Color',
              containerSize: 'Container size',
              description: 'Description',
              active: 'Status',
            },
            translationBadge: '{{locale}}: {{value}}',
            dialog: {
              createTitle: 'Create waste fraction',
              createDescription: 'Create a new fraction for further tour and calendar maintenance.',
              editTitle: 'Edit waste fraction',
              editDescription: 'Change name, color and visibility of the fraction.',
            },
            messages: {
              createSuccess: 'The waste fraction was created.',
              updateSuccess: 'The waste fraction was updated.',
              saveError: 'The waste fraction could not be saved.',
              saveForbidden: 'Missing permission to save waste fractions.',
            },
          },
          regions: {
            title: 'Regions',
            description: 'Maintain regions as the second small master-data path with its own dialog.',
            regionId: 'Region ID: {{value}}',
            actions: {
              openCreate: 'Create region',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save region',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              name: 'Name',
            },
            dialog: {
              createTitle: 'Create region',
              createDescription: 'Create a new region for the geographic hierarchy.',
              editTitle: 'Edit region',
              editDescription: 'Change the region name.',
            },
            messages: {
              createSuccess: 'The waste region was created.',
              updateSuccess: 'The waste region was updated.',
              saveError: 'The waste region could not be saved.',
              saveForbidden: 'Missing permission to save waste regions.',
            },
          },
          cities: {
            title: 'Cities',
            description: 'Maintain cities with optional region assignment as the first relational master-data path.',
            cityId: 'City ID: {{value}}',
            regionId: 'Region ID: {{value}}',
            actions: {
              openCreate: 'Create city',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save city',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              name: 'Name',
              regionId: 'Region',
              regionUnset: 'No region',
            },
            dialog: {
              createTitle: 'Create city',
              createDescription: 'Create a city and assign it to a region when needed.',
              editTitle: 'Edit city',
              editDescription: 'Change the city name or region assignment.',
            },
            messages: {
              createSuccess: 'The waste city was created.',
              updateSuccess: 'The waste city was updated.',
              saveError: 'The waste city could not be saved.',
              saveForbidden: 'Missing permission to save waste cities.',
            },
          },
          streets: {
            title: 'Streets',
            description: 'Maintain streets as a dedicated address path below cities.',
            streetId: 'Street ID: {{value}}',
            cityId: 'City ID: {{value}}',
            actions: {
              openCreate: 'Create street',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save street',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              name: 'Name',
              cityId: 'City',
              cityUnset: 'Select city',
            },
            dialog: {
              createTitle: 'Create street',
              createDescription: 'Create a street and assign it to a city.',
              editTitle: 'Edit street',
              editDescription: 'Adjust the street name or its linked city.',
            },
            messages: {
              createSuccess: 'The waste street was created.',
              updateSuccess: 'The waste street was updated.',
              saveError: 'The waste street could not be saved.',
              saveForbidden: 'Missing permission to save waste streets.',
            },
          },
          houseNumbers: {
            title: 'House numbers',
            description: 'Maintain house numbers as the final direct path of the address hierarchy.',
            houseNumberId: 'House number ID: {{value}}',
            streetId: 'Street ID: {{value}}',
            actions: {
              openCreate: 'Create house number',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save house number',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              number: 'House number',
              streetId: 'Street',
              streetUnset: 'Select street',
            },
            dialog: {
              createTitle: 'Create house number',
              createDescription: 'Create a house number and assign it to a street.',
              editTitle: 'Edit house number',
              editDescription: 'Adjust the house number or its linked street.',
            },
            messages: {
              createSuccess: 'The waste house number was created.',
              updateSuccess: 'The waste house number was updated.',
              saveError: 'The waste house number could not be saved.',
              saveForbidden: 'Missing permission to save waste house numbers.',
            },
          },
          collectionLocations: {
            title: 'Collection locations',
            description: 'Maintain concrete collection locations with geographic selection down to house-number level.',
            actions: {
              openCreate: 'Create collection location',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save collection location',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              regionId: 'Region',
              regionUnset: 'All regions',
              cityId: 'City',
              cityUnset: 'Select city',
              streetId: 'Street',
              streetUnset: 'All streets',
              houseNumberId: 'House number',
              houseNumberUnset: 'All house numbers',
              active: 'Status',
            },
            dialog: {
              createTitle: 'Create collection location',
              createDescription: 'Create a new collection location from region, city, street and house number.',
              editTitle: 'Edit collection location',
              editDescription: 'Adjust the geographic assignment and visibility of the collection location.',
            },
            meta: {
              locationId: 'Location ID: {{value}}',
              allStreets: 'All streets',
              allHouseNumbers: 'All house numbers',
            },
            messages: {
              createSuccess: 'The waste collection location was created.',
              updateSuccess: 'The waste collection location was updated.',
              saveError: 'The waste collection location could not be saved.',
              saveForbidden: 'Missing permission to save waste collection locations.',
            },
            bulk: {
              actions: {
                openAssign: 'Assign tour to {{value}} selected',
                selectAllFiltered: 'Select all filtered collection locations',
                cancel: 'Cancel',
                assign: 'Assign tour',
                saving: 'Saving…',
              },
              fields: {
                tourId: 'Tour',
                tourUnset: 'Select tour',
                startDate: 'Start date',
                endDate: 'End date',
              },
              dialog: {
                title: 'Bulk assign tour',
                description: 'Assign a tour to {{value}} selected collection locations.',
              },
              selectedTitle: 'Selected collection locations',
              meta: {
                selectedCount: '{{value}} selected',
              },
              messages: {
                assignSuccess: 'The waste tour assignments were created in bulk.',
                assignError: 'The waste tour assignments could not be created in bulk.',
                assignForbidden: 'Missing permission to create waste tour assignments in bulk.',
              },
            },
          },
        },
        tools: {
          imports: {
            title: 'Imports',
            description:
              'Starts domain-near waste imports as a thin shell on top of the generic host job capability.',
            profileLabel: 'Import profile',
            blobRefLabel: 'Source reference (blob ref)',
            sourceFormatLabel: 'Source format',
            sourceFormats: {
              csv: 'CSV',
              xlsx: 'Excel (.xlsx)',
            },
            dryRunLabel: 'Preflight only (dry run)',
            templateColumns: 'Canonical import columns',
          },
          migrations: {
            title: 'Migrations',
            description: 'Starts asynchronous host migration jobs against the active waste data source.',
            schemaLabel: 'Target schema',
            versionLabel: 'Requested by version',
          },
          seed: {
            title: 'Seed',
            description: 'Populates the waste data source through the generic job capability with the baseline.',
          },
          reset: {
            title: 'Reset',
            description: 'Reset remains a high-risk path and requires an explicit confirmation token.',
            tokenLabel: 'Confirmation token',
            confirmTitle: 'Start reset now?',
            confirmDescription: 'This reset is high risk. Confirm the operation explicitly with the token.',
            confirmCancel: 'Cancel',
            confirmAction: 'Confirm reset',
          },
          actions: {
            startImport: 'Start import',
            startMigrations: 'Start migrations',
            startSeed: 'Start seed',
            startReset: 'Start reset',
            starting: 'Starting…',
            downloadTemplate: 'Download template',
            openJob: 'Open job',
          },
          messages: {
            jobStarted: 'Job {{jobId}} was started.',
            jobStartError: 'The waste job could not be started.',
            forbidden: 'Missing permission for this waste operation.',
            importValidationError: 'Import requires an import profile and a valid source reference.',
            resetValidationError: 'Reset requires a valid confirmation token.',
          },
          meta: {
            lastJobTitle: 'Last technical job',
            lastJobDescription: 'Most recently started waste host job with technical status.',
            noJobYet: 'No technical waste job has been started yet.',
            noJobStatus: 'No job',
            technicalHistoryTitle: 'Technical events',
            technicalHistoryDescription:
              'Shows the latest technical waste events with distinct outcomes for start, success, and failure.',
            noTechnicalHistory: 'No technical waste events yet.',
            jobId: 'Job: {{value}}',
            jobType: 'Type: {{value}}',
            jobStatus: 'Status: {{value}}',
            jobIdLabel: 'Job',
            jobTypeLabel: 'Type',
            jobStatusLabel: 'Status',
          },
        },
        tours: {
          actions: {
            openCreate: 'Create tour',
            edit: 'Edit',
            cancel: 'Cancel',
            create: 'Save tour',
            save: 'Save changes',
            saving: 'Saving…',
          },
          fields: {
            name: 'Name',
            description: 'Description',
            recurrence: 'Recurrence',
            recurrenceUnset: 'No recurrence',
            firstDate: 'First date',
            endDate: 'End date',
            customDates: 'Custom dates',
            customDatesPlaceholder: '2026-05-12 | Special pickup\n2026-05-26',
            wasteFractions: 'Waste fractions',
            noFractionsAvailable: 'No waste fractions are available yet.',
            active: 'Status',
          },
          dialog: {
            createTitle: 'Create tour',
            createDescription: 'Create the first editable tour including fractions and date logic.',
            editTitle: 'Edit tour',
            editDescription: 'Adjust fractions, recurrence and date logic for the tour.',
          },
          meta: {
            count: '{{value}} tours',
            recurrence: 'Recurrence: {{value}}',
            fractionCount: 'Fractions: {{value}}',
            locationCount: 'Collection locations: {{value}}',
            dateRange: 'Date range: {{value}}',
            tourId: 'Tour ID: {{value}}',
          },
          recurrence: {
            weekly: 'Weekly',
            biweekly: 'Biweekly',
            fourweekly: 'Every four weeks',
            yearly: 'Yearly',
            onDemand: 'On demand',
            custom: 'Custom',
          },
          customDates: {
            title: 'Custom dates',
          },
          messages: {
            loading: 'Loading tours.',
            loadError: 'Waste tours could not be loaded.',
            loadForbidden: 'Missing permission for waste tours.',
            emptyTitle: 'No tours found',
            emptyBody: 'Adjust the filters or provide tours in the waste data source.',
            createSuccess: 'The waste tour was created.',
            updateSuccess: 'The waste tour was updated.',
            saveError: 'The waste tour could not be saved.',
            saveForbidden: 'Missing permission to save waste tours.',
          },
        },
        scheduling: {
          global: {
            title: 'Global shifts',
            description: 'Shifts with global effect across multiple tours.',
            cardTitle: 'Global shift {{value}}',
            actions: {
              openCreate: 'Create global shift',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save shift',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              originalDate: 'Original date',
              actualDate: 'Shifted date',
              reasonType: 'Reason',
              reasonTypeUnset: 'Select reason',
              reasonKey: 'Reason key',
              description: 'Description',
              hasYear: 'Year-specific',
              tourIds: 'Affected tours',
              noToursAvailable: 'No tours are available yet.',
            },
            dialog: {
              createTitle: 'Create global shift',
              createDescription: 'Create a global shift with optionally affected tours.',
              editTitle: 'Edit global shift',
              editDescription: 'Adjust date, description or affected tours.',
            },
            messages: {
              createSuccess: 'The global waste shift was created.',
              updateSuccess: 'The global waste shift was updated.',
              saveError: 'The global waste shift could not be saved.',
              saveForbidden: 'Missing permission to save global waste shifts.',
            },
          },
          tour: {
            title: 'Tour-related shifts',
            description: 'Targeted single-date shifts for specific tours.',
            cardTitle: 'Tour {{value}}',
            actions: {
              openCreate: 'Create tour shift',
              edit: 'Edit',
              cancel: 'Cancel',
              create: 'Save shift',
              save: 'Save changes',
              saving: 'Saving…',
            },
            fields: {
              tourId: 'Tour',
              tourUnset: 'Select tour',
              originalDate: 'Original date',
              actualDate: 'Shifted date',
              reasonType: 'Reason',
              reasonTypeUnset: 'Select reason',
              reasonKey: 'Reason key',
              followUpMode: 'Follow-up effect',
              followUpModeUnset: 'No follow-up effect',
              description: 'Description',
              hasYear: 'Year-specific',
            },
            dialog: {
              createTitle: 'Create tour-related shift',
              createDescription: 'Create a targeted single-date shift for a specific tour.',
              editTitle: 'Edit tour-related shift',
              editDescription: 'Adjust the tour, date or description of the single-date shift.',
            },
            messages: {
              createSuccess: 'The tour-related waste shift was created.',
              updateSuccess: 'The tour-related waste shift was updated.',
              saveError: 'The tour-related waste shift could not be saved.',
              saveForbidden: 'Missing permission to save tour-related waste shifts.',
            },
          },
          meta: {
            globalCount: '{{value}} global shifts',
            tourCount: '{{value}} tour shifts',
            hasYear: 'Year-specific: {{value}}',
            affectedTours: 'Affected tours: {{value}}',
            reasonType: 'Reason: {{value}}',
            reasonKey: 'Key: {{value}}',
            followUpMode: 'Follow-up: {{value}}',
          },
          reasonTypes: {
            holiday: 'Holiday',
            'global-deviation': 'Global deviation',
            'manual-adjustment': 'Manual adjustment',
            'operational-disruption': 'Operational disruption',
            weather: 'Weather',
            other: 'Other',
          },
          followUpModes: {
            none: 'None',
            'propagate-series': 'Propagate series',
            'mark-follow-up-dates': 'Mark follow-up dates',
          },
          messages: {
            loading: 'Loading scheduling shifts.',
            loadError: 'Waste scheduling shifts could not be loaded.',
            loadForbidden: 'Missing permission for waste scheduling shifts.',
            emptyTitle: 'No scheduling shifts found',
            emptyBody: 'Adjust the filters or provide date shifts in the waste data source.',
          },
        },
        permissions: {
          read: { title: 'Read waste calendar' },
          masterDataManage: { title: 'Manage master data' },
          toursManage: { title: 'Manage tours' },
          schedulingManage: { title: 'Manage schedule deviations' },
          importExecute: { title: 'Run imports' },
          seedExecute: { title: 'Run seed' },
          resetExecute: { title: 'Run reset' },
          settingsManage: { title: 'Manage settings' },
        },
      },
    },
  },
};
