import type { WasteCityRecord, WasteRegionRecord, WasteStreetRecord } from '@sva/plugin-sdk';
import { usePluginTranslation } from '@sva/plugin-sdk';
import { Button, Checkbox, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Input, Select, StudioField, StudioFieldGroup } from '@sva/studio-ui-react';
import type { FormEvent } from 'react';

import { StatusNotice, type StatusMessage } from './waste-management.page.support.js';
import type { CityFormState, FractionFormState, HouseNumberFormState, RegionFormState, StreetFormState } from './waste-management.master-data.forms.js';

type BaseProps<TForm> = {
  readonly open: boolean;
  readonly mode: 'create' | 'edit';
  readonly form: TForm;
  readonly saving: boolean;
  readonly message: StatusMessage | null;
  readonly onOpenChange: (open: boolean) => void;
  readonly onChange: (patch: Partial<TForm>) => void;
  readonly onSubmit: (event: FormEvent<HTMLFormElement>) => void;
};

export const FractionDialog = ({ open, mode, form, saving, message, onOpenChange, onChange, onSubmit }: BaseProps<FractionFormState>) => {
  const pt = usePluginTranslation('wasteManagement');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'create' ? pt('masterData.fractions.dialog.createTitle') : pt('masterData.fractions.dialog.editTitle')}</DialogTitle><DialogDescription>{mode === 'create' ? pt('masterData.fractions.dialog.createDescription') : pt('masterData.fractions.dialog.editDescription')}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><StatusNotice message={message} /><StudioFieldGroup><StudioField id="waste-fraction-name" label={pt('masterData.fractions.fields.name')}><Input id="waste-fraction-name" value={form.name} onChange={(event) => onChange({ name: event.target.value })} /></StudioField><StudioField id="waste-fraction-name-de" label={pt('masterData.fractions.fields.translationDe')}><Input id="waste-fraction-name-de" value={form.translations.de ?? ''} onChange={(event) => onChange({ translations: { ...form.translations, de: event.target.value } })} /></StudioField><StudioField id="waste-fraction-name-en" label={pt('masterData.fractions.fields.translationEn')}><Input id="waste-fraction-name-en" value={form.translations.en ?? ''} onChange={(event) => onChange({ translations: { ...form.translations, en: event.target.value } })} /></StudioField><StudioField id="waste-fraction-color" label={pt('masterData.fractions.fields.color')}><Input id="waste-fraction-color" value={form.color} onChange={(event) => onChange({ color: event.target.value })} /></StudioField><StudioField id="waste-fraction-container-size" label={pt('masterData.fractions.fields.containerSize')}><Input id="waste-fraction-container-size" value={form.containerSize} onChange={(event) => onChange({ containerSize: event.target.value })} /></StudioField><StudioField id="waste-fraction-description" label={pt('masterData.fractions.fields.description')}><Input id="waste-fraction-description" value={form.description} onChange={(event) => onChange({ description: event.target.value })} /></StudioField><StudioField id="waste-fraction-active" label={pt('masterData.fractions.fields.active')}><div className="flex items-center gap-3"><Checkbox id="waste-fraction-active" checked={form.active} onChange={(event) => onChange({ active: event.currentTarget.checked })} /><span className="text-sm text-muted-foreground">{form.active ? pt('common.active') : pt('common.inactive')}</span></div></StudioField></StudioFieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{pt('masterData.fractions.actions.cancel')}</Button><Button type="submit" disabled={saving}>{saving ? pt('masterData.fractions.actions.saving') : mode === 'create' ? pt('masterData.fractions.actions.create') : pt('masterData.fractions.actions.save')}</Button></DialogFooter></form></DialogContent></Dialog>;
};

export const RegionDialog = ({ open, mode, form, saving, message, onOpenChange, onChange, onSubmit }: BaseProps<RegionFormState>) => {
  const pt = usePluginTranslation('wasteManagement');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'create' ? pt('masterData.regions.dialog.createTitle') : pt('masterData.regions.dialog.editTitle')}</DialogTitle><DialogDescription>{mode === 'create' ? pt('masterData.regions.dialog.createDescription') : pt('masterData.regions.dialog.editDescription')}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><StatusNotice message={message} /><StudioFieldGroup><StudioField id="waste-region-name" label={pt('masterData.regions.fields.name')}><Input id="waste-region-name" value={form.name} onChange={(event) => onChange({ name: event.target.value })} /></StudioField></StudioFieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{pt('masterData.regions.actions.cancel')}</Button><Button type="submit" disabled={saving}>{saving ? pt('masterData.regions.actions.saving') : mode === 'create' ? pt('masterData.regions.actions.create') : pt('masterData.regions.actions.save')}</Button></DialogFooter></form></DialogContent></Dialog>;
};

export const CityDialog = ({ open, mode, form, regions, saving, message, onOpenChange, onChange, onSubmit }: BaseProps<CityFormState> & { readonly regions: readonly WasteRegionRecord[] }) => {
  const pt = usePluginTranslation('wasteManagement');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'create' ? pt('masterData.cities.dialog.createTitle') : pt('masterData.cities.dialog.editTitle')}</DialogTitle><DialogDescription>{mode === 'create' ? pt('masterData.cities.dialog.createDescription') : pt('masterData.cities.dialog.editDescription')}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><StatusNotice message={message} /><StudioFieldGroup><StudioField id="waste-city-name" label={pt('masterData.cities.fields.name')}><Input id="waste-city-name" name="name" value={form.name} onChange={(event) => onChange({ name: event.target.value })} /></StudioField><StudioField id="waste-city-region-id" label={pt('masterData.cities.fields.regionId')}><Select id="waste-city-region-id" aria-label={pt('masterData.cities.fields.regionId')} name="regionId" value={form.regionId} onChange={(event) => onChange({ regionId: event.target.value })}><option value="">{pt('masterData.cities.fields.regionUnset')}</option>{regions.map((region) => <option key={region.id} value={region.id}>{region.name}</option>)}</Select></StudioField></StudioFieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{pt('masterData.cities.actions.cancel')}</Button><Button type="submit" disabled={saving}>{saving ? pt('masterData.cities.actions.saving') : mode === 'create' ? pt('masterData.cities.actions.create') : pt('masterData.cities.actions.save')}</Button></DialogFooter></form></DialogContent></Dialog>;
};

export const StreetDialog = ({ open, mode, form, cities, saving, message, onOpenChange, onChange, onSubmit }: BaseProps<StreetFormState> & { readonly cities: readonly WasteCityRecord[] }) => {
  const pt = usePluginTranslation('wasteManagement');
  const selectedCityId = form.cityId || (cities.length === 1 ? cities[0]?.id ?? '' : '');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'create' ? pt('masterData.streets.dialog.createTitle') : pt('masterData.streets.dialog.editTitle')}</DialogTitle><DialogDescription>{mode === 'create' ? pt('masterData.streets.dialog.createDescription') : pt('masterData.streets.dialog.editDescription')}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><StatusNotice message={message} /><StudioFieldGroup><StudioField id="waste-street-name" label={pt('masterData.streets.fields.name')}><Input id="waste-street-name" name="name" value={form.name} onChange={(event) => onChange({ name: event.target.value })} /></StudioField><StudioField id="waste-street-city-id" label={pt('masterData.streets.fields.cityId')}><Select id="waste-street-city-id" aria-label={pt('masterData.streets.fields.cityId')} name="cityId" value={selectedCityId} onChange={(event) => onChange({ cityId: event.target.value })}><option value="">{pt('masterData.streets.fields.cityUnset')}</option>{cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</Select></StudioField></StudioFieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{pt('masterData.streets.actions.cancel')}</Button><Button type="submit" disabled={saving}>{saving ? pt('masterData.streets.actions.saving') : mode === 'create' ? pt('masterData.streets.actions.create') : pt('masterData.streets.actions.save')}</Button></DialogFooter></form></DialogContent></Dialog>;
};

export const HouseNumberDialog = ({ open, mode, form, streets, saving, message, onOpenChange, onChange, onSubmit }: BaseProps<HouseNumberFormState> & { readonly streets: readonly WasteStreetRecord[] }) => {
  const pt = usePluginTranslation('wasteManagement');
  const selectedStreetId = form.streetId || (streets.length === 1 ? streets[0]?.id ?? '' : '');
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'create' ? pt('masterData.houseNumbers.dialog.createTitle') : pt('masterData.houseNumbers.dialog.editTitle')}</DialogTitle><DialogDescription>{mode === 'create' ? pt('masterData.houseNumbers.dialog.createDescription') : pt('masterData.houseNumbers.dialog.editDescription')}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={onSubmit}><StatusNotice message={message} /><StudioFieldGroup><StudioField id="waste-house-number-value" label={pt('masterData.houseNumbers.fields.number')}><Input id="waste-house-number-value" name="number" value={form.number} onChange={(event) => onChange({ number: event.target.value })} /></StudioField><StudioField id="waste-house-number-street-id" label={pt('masterData.houseNumbers.fields.streetId')}><Select id="waste-house-number-street-id" aria-label={pt('masterData.houseNumbers.fields.streetId')} name="streetId" value={selectedStreetId} onChange={(event) => onChange({ streetId: event.target.value })}><option value="">{pt('masterData.houseNumbers.fields.streetUnset')}</option>{streets.map((street) => <option key={street.id} value={street.id}>{street.name}</option>)}</Select></StudioField></StudioFieldGroup><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{pt('masterData.houseNumbers.actions.cancel')}</Button><Button type="submit" disabled={saving}>{saving ? pt('masterData.houseNumbers.actions.saving') : mode === 'create' ? pt('masterData.houseNumbers.actions.create') : pt('masterData.houseNumbers.actions.save')}</Button></DialogFooter></form></DialogContent></Dialog>;
};
