export const scopedMainserverProjectionUpsertSql = `
INSERT INTO iam.content_list_projection (
  id,
  instance_id,
  projection_scope_key,
  organization_id,
  owner_user_id,
  owner_organization_id,
  content_type,
  title,
  published_at,
  publish_from,
  publish_until,
  created_at,
  created_by,
  updated_at,
  updated_by,
  author_display_mode,
  author_display_name,
  source_data_provider_id,
  source_data_provider_name,
  credential_source,
  credential_fingerprint,
  authorization_mode,
  payload_json,
  status,
  validation_state,
  history_ref,
  current_revision_ref,
  last_audit_event_ref,
  source_system,
  source_entity_type,
  source_entity_id,
  projection_updated_at
)
SELECT
  item.id,
  item.instance_id,
  item.projection_scope_key,
  item.organization_id::uuid,
  item.owner_user_id::uuid,
  item.owner_organization_id::uuid,
  item.content_type,
  item.title,
  item.published_at::timestamptz,
  item.publish_from::timestamptz,
  item.publish_until::timestamptz,
  item.created_at::timestamptz,
  item.created_by,
  item.updated_at::timestamptz,
  item.updated_by,
  item.author_display_mode,
  item.author_display_name,
  item.source_data_provider_id,
  item.source_data_provider_name,
  item.credential_source,
  item.credential_fingerprint,
  item.authorization_mode,
  item.payload_json::jsonb,
  item.status,
  item.validation_state,
  item.history_ref,
  NULLIF(item.current_revision_ref, ''),
  NULLIF(item.last_audit_event_ref, ''),
  'mainserver',
  item.source_entity_type,
  item.source_entity_id,
  NOW()
FROM jsonb_to_recordset($1::jsonb) AS item(
  id text,
  instance_id text,
  projection_scope_key text,
  organization_id text,
  owner_user_id text,
  owner_organization_id text,
  content_type text,
  title text,
  published_at text,
  publish_from text,
  publish_until text,
  created_at text,
  created_by text,
  updated_at text,
  updated_by text,
  author_display_mode text,
  author_display_name text,
  source_data_provider_id text,
  source_data_provider_name text,
  credential_source text,
  credential_fingerprint text,
  authorization_mode text,
  payload_json jsonb,
  status text,
  validation_state text,
  history_ref text,
  current_revision_ref text,
  last_audit_event_ref text,
  source_entity_type text,
  source_entity_id text
)
ON CONFLICT ON CONSTRAINT content_list_projection_scope_key
DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  published_at = EXCLUDED.published_at,
  publish_from = EXCLUDED.publish_from,
  publish_until = EXCLUDED.publish_until,
  created_at = EXCLUDED.created_at,
  created_by = EXCLUDED.created_by,
  updated_at = EXCLUDED.updated_at,
  updated_by = EXCLUDED.updated_by,
  author_display_mode = EXCLUDED.author_display_mode,
  author_display_name = EXCLUDED.author_display_name,
  source_data_provider_id = EXCLUDED.source_data_provider_id,
  source_data_provider_name = EXCLUDED.source_data_provider_name,
  credential_source = EXCLUDED.credential_source,
  credential_fingerprint = EXCLUDED.credential_fingerprint,
  authorization_mode = EXCLUDED.authorization_mode,
  payload_json = EXCLUDED.payload_json,
  status = EXCLUDED.status,
  validation_state = EXCLUDED.validation_state,
  history_ref = EXCLUDED.history_ref,
  current_revision_ref = EXCLUDED.current_revision_ref,
  last_audit_event_ref = EXCLUDED.last_audit_event_ref,
  projection_updated_at = NOW();
`;

export const legacyMainserverProjectionUpsertSql = `
INSERT INTO iam.content_list_projection (
  id,
  instance_id,
  organization_id,
  owner_user_id,
  owner_organization_id,
  content_type,
  title,
  published_at,
  publish_from,
  publish_until,
  created_at,
  created_by,
  updated_at,
  updated_by,
  author_display_mode,
  author_display_name,
  source_data_provider_id,
  source_data_provider_name,
  credential_source,
  credential_fingerprint,
  authorization_mode,
  payload_json,
  status,
  validation_state,
  history_ref,
  current_revision_ref,
  last_audit_event_ref,
  source_system,
  source_entity_type,
  source_entity_id,
  projection_updated_at
)
SELECT
  item.id,
  item.instance_id,
  item.organization_id::uuid,
  item.owner_user_id::uuid,
  item.owner_organization_id::uuid,
  item.content_type,
  item.title,
  item.published_at::timestamptz,
  item.publish_from::timestamptz,
  item.publish_until::timestamptz,
  item.created_at::timestamptz,
  item.created_by,
  item.updated_at::timestamptz,
  item.updated_by,
  item.author_display_mode,
  item.author_display_name,
  item.source_data_provider_id,
  item.source_data_provider_name,
  item.credential_source,
  item.credential_fingerprint,
  item.authorization_mode,
  item.payload_json::jsonb,
  item.status,
  item.validation_state,
  item.history_ref,
  NULLIF(item.current_revision_ref, ''),
  NULLIF(item.last_audit_event_ref, ''),
  'mainserver',
  item.source_entity_type,
  item.source_entity_id,
  NOW()
FROM jsonb_to_recordset($1::jsonb) AS item(
  id text,
  instance_id text,
  organization_id text,
  owner_user_id text,
  owner_organization_id text,
  content_type text,
  title text,
  published_at text,
  publish_from text,
  publish_until text,
  created_at text,
  created_by text,
  updated_at text,
  updated_by text,
  author_display_mode text,
  author_display_name text,
  source_data_provider_id text,
  source_data_provider_name text,
  credential_source text,
  credential_fingerprint text,
  authorization_mode text,
  payload_json jsonb,
  status text,
  validation_state text,
  history_ref text,
  current_revision_ref text,
  last_audit_event_ref text,
  source_entity_type text,
  source_entity_id text
)
ON CONFLICT ON CONSTRAINT content_list_projection_scope_key
DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  published_at = EXCLUDED.published_at,
  publish_from = EXCLUDED.publish_from,
  publish_until = EXCLUDED.publish_until,
  created_at = EXCLUDED.created_at,
  created_by = EXCLUDED.created_by,
  updated_at = EXCLUDED.updated_at,
  updated_by = EXCLUDED.updated_by,
  author_display_mode = EXCLUDED.author_display_mode,
  author_display_name = EXCLUDED.author_display_name,
  source_data_provider_id = EXCLUDED.source_data_provider_id,
  source_data_provider_name = EXCLUDED.source_data_provider_name,
  credential_source = EXCLUDED.credential_source,
  credential_fingerprint = EXCLUDED.credential_fingerprint,
  authorization_mode = EXCLUDED.authorization_mode,
  payload_json = EXCLUDED.payload_json,
  status = EXCLUDED.status,
  validation_state = EXCLUDED.validation_state,
  history_ref = EXCLUDED.history_ref,
  current_revision_ref = EXCLUDED.current_revision_ref,
  last_audit_event_ref = EXCLUDED.last_audit_event_ref,
  projection_updated_at = NOW();
`;
