import type { SchemaGuardReport } from '../../../packages/auth-runtime/src/iam-account-management/schema-guard.ts';
import type { RuntimeProfile } from '../../../packages/core/src/runtime-profile.ts';
import type { AcceptanceDeployOptions, AcceptanceDeployReport, AcceptanceDeployStep, AcceptanceProbeResult, DoctorCheck, DoctorReport, RemoteRuntimeProfile, TenantRuntimeTarget } from '../runtime-env.shared.ts';
import type { ComposeDocument, ServiceContract } from './deploy-project.ts';
import type { RemoteServiceContract } from './remote-service-spec.ts';
import type { RemoteRuntimeConfigDeps, RuntimeCommandRunnerDeps, RuntimeContractDeps } from './runtime-deps.types.ts';
import type {
  LocalTenantSecretState,
  SchemaSnapshotVerificationReport,
} from './doctor-db-checks.types.ts';
import type { LocalState } from './local-runtime.ts';

export type RuntimeRemoteBundleDeps = RuntimeCommandRunnerDeps & RemoteRuntimeConfigDeps & RuntimeContractDeps & {
  acceptanceRemoteStateOps: {
    buildSwarmAppTaskProbe: (env: NodeJS.ProcessEnv) => AcceptanceProbeResult;
    readRemoteStackEvidence: (env: NodeJS.ProcessEnv) => Promise<{ channel: 'docker' | 'portainer-api' | 'quantum-cli'; hasRunningService: (serviceName: string) => boolean; summary: string }>;
    runBootstrapJobAgainstAcceptance: (env: NodeJS.ProcessEnv, runtimeProfile: RemoteRuntimeProfile, reportId: string) => Promise<{ cleanup: () => Promise<void>; durationMs?: number; exitCode?: number; jobServiceName: string; jobStackName: string; logTail?: string; state: string; taskId?: string; taskMessage?: string }>;
    runMigrationJobAgainstAcceptance: (env: NodeJS.ProcessEnv, runtimeProfile: RemoteRuntimeProfile, reportId: string) => Promise<{ cleanup: () => Promise<void>; durationMs?: number; exitCode?: number; jobServiceName: string; jobStackName: string; logTail?: string; state: string; taskId?: string; taskMessage?: string }>;
  };
  acceptanceRuntimeCore: {
    acceptanceMaintenanceOps: { createBaseAcceptanceDeployReport: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv, options: AcceptanceDeployOptions, migrationFiles: readonly string[]) => AcceptanceDeployReport };
    buildAcceptanceIngressConsistencyCheck: (env: NodeJS.ProcessEnv) => Promise<DoctorCheck>;
    buildAcceptanceLiveSpecCheck: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv, options: AcceptanceDeployOptions) => Promise<DoctorCheck>;
    buildAcceptancePostgresCheck: (env: NodeJS.ProcessEnv) => DoctorCheck;
    buildAcceptanceServiceCheck: (env: NodeJS.ProcessEnv) => Promise<DoctorCheck>;
    buildAppPrincipalReadinessCheck: (env: NodeJS.ProcessEnv) => Promise<DoctorCheck>;
    buildSwarmServicePresenceProbe: (env: NodeJS.ProcessEnv) => AcceptanceProbeResult;
    captureAcceptanceStackStatus: (env: NodeJS.ProcessEnv) => Promise<{ services?: string; tasks?: string }>;
    deployAcceptanceStack: (env: NodeJS.ProcessEnv) => void;
    migrateAcceptance: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv) => Promise<void>;
    resetAcceptance: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv, verifyPostReset: () => Promise<void>) => Promise<void>;
    writeAcceptanceDeployReport: (report: AcceptanceDeployReport) => void;
  };
  assertComposeServiceIngressLabels: (compose: ComposeDocument, serviceName: string) => ServiceContract;
  assertComposeServiceNetworks: (compose: ComposeDocument, serviceName: string, expectedNetworks: readonly string[]) => ServiceContract;
  assertDeterministicRemoteMutationContext: (env: NodeJS.ProcessEnv, runtimeProfile: RemoteRuntimeProfile, command: 'deploy') => { mode: 'ci' | 'ci-runner' | 'local-emergency' | 'local-operator' };
  assertRuntimeEnv: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => void;
  buildAcceptanceReportPaths: typeof import('../runtime-env.shared.ts').buildAcceptanceReportPaths;
  buildGuardrailDoctorChecks: (runtimeProfile: RuntimeProfile, options: { readonly env: NodeJS.ProcessEnv }) => Promise<readonly DoctorCheck[]>;
  buildImagePlatformDoctorCheck: (env: NodeJS.ProcessEnv, options?: AcceptanceDeployOptions) => DoctorCheck;
  buildLocalInstanceRegistryReconciliationInput: (env: NodeJS.ProcessEnv) => { allowedInstanceIds: readonly string[]; reconcileMode: string } | null;
  buildLocalProvisioningWorkerCheckBase: (runtimeProfile: RuntimeProfile, workerState: LocalState | null, isProcessAlive: (pid: number) => boolean) => DoctorCheck;
  buildProdParityProbePlan: typeof import('../runtime-env.shared.ts').buildProdParityProbePlan;
  buildQuantumDeployComposeDocument: (compose: ComposeDocument) => ComposeDocument;
  buildStudioImageVerifyEvidenceCheck: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv, options?: AcceptanceDeployOptions) => DoctorCheck;
  buildTrustedForwardedHeaders: typeof import('../runtime-env.shared.ts').buildTrustedForwardedHeaders;
  checkHttpHealth: (url: string) => Promise<{ payload?: unknown; response: { ok: boolean; status: number } }>;
  cliOptions: unknown;
  commandExists: (commandName: string) => boolean;
  collectLocalInstanceIdentityDrift: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => readonly unknown[];
  createDbSqlRunner: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => (sql: string) => string;
  createProbeResult: (input: {
    details?: Readonly<Record<string, unknown>>;
    durationMs: number;
    httpStatus?: number;
    message: string;
    name: string;
    scope: AcceptanceProbeResult['scope'];
    status: AcceptanceProbeResult['status'];
    target: string;
  }) => AcceptanceProbeResult;
  createStepResult: (name: AcceptanceDeployStep['name'], startedAt: number, status: AcceptanceDeployStep['status'], summary: string, details?: Readonly<Record<string, unknown>>) => AcceptanceDeployStep;
  deployReportDir: string;
  doctorRuntime: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => Promise<DoctorReport>;
  ensureDirs: () => void;
  finalizeDoctorReport: (runtimeProfile: RuntimeProfile, checks: readonly DoctorCheck[]) => DoctorReport;
  getGitCommitSha: () => string | undefined;
  getRuntimeProfileDefinition: (runtimeProfile: RuntimeProfile) => { isLocal: boolean };
  hasLocalEmergencyRemoteMutationOverride: (env: NodeJS.ProcessEnv) => boolean;
  inspectRemoteServiceContract: (env: NodeJS.ProcessEnv, input: { quantumEndpoint: string; serviceName: string; stackName: string }) => Promise<RemoteServiceContract | null>;
  isExpectedOidcRedirect: (location: string, env: NodeJS.ProcessEnv) => boolean;
  isMainserverCheckRequired: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => boolean;
  isMigrationStatusCheckRequired: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => boolean;
  isMockAuthRuntimeProfile: (runtimeProfile: RuntimeProfile) => boolean;
  isProcessAlive: (pid: number) => boolean;
  isRemoteRuntimeProfile: (runtimeProfile: RuntimeProfile) => runtimeProfile is RemoteRuntimeProfile;
  jsonOutput: boolean;
  listGooseMigrationFiles: () => readonly string[];
  loadActiveLocalTenantSecretStates: (env: NodeJS.ProcessEnv) => Promise<readonly LocalTenantSecretState[]>;
  loadRegistryTenantTargets: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv, options?: { readonly limit?: number }) => readonly TenantRuntimeTarget[];
  localWorkerStateFile: string;
  parseInstanceIdList: (value: string | undefined) => readonly string[];
  parseJsonFromCommandOutput: <T>(value: string) => T;
  parseRuntimeProfile: (value: string | undefined) => RuntimeProfile | undefined;
  precheckAcceptance: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv, options?: AcceptanceDeployOptions) => Promise<DoctorReport>;
  printJsonIfRequested: (payload: unknown) => void;
  readLocalWorkerState: (path: string) => { [key: string]: unknown } | null;
  resolveAcceptanceDeployOptions: (env: NodeJS.ProcessEnv, cliOptions: unknown, runtimeProfile: RemoteRuntimeProfile) => AcceptanceDeployOptions;
  runSchemaGuard: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => SchemaGuardReport;
  shouldSkipQuantumPrePull: (env: NodeJS.ProcessEnv) => boolean;
  sqlIdentifier: (value: string) => string;
  sqlLiteral: (value: string) => string;
  summarizeProcessOutput: (value: string) => string;
  summarizeSchemaGuardFailures: (report: SchemaGuardReport) => string | undefined;
  toDoctorCheck: (name: string, status: DoctorCheck['status'], code: string, message: string, details?: Readonly<Record<string, unknown>>) => DoctorCheck;
  validateRuntimeProfileEnv: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => { derived: readonly string[] | Record<string, unknown>; invalid: readonly string[]; missing: readonly string[]; placeholders: readonly string[] };
  verifyLocalDbSchemaSnapshot: (env: NodeJS.ProcessEnv) => SchemaSnapshotVerificationReport;
  wait: (ms: number) => Promise<unknown>;
  withoutDebugEnv: (env: NodeJS.ProcessEnv) => NodeJS.ProcessEnv;
};
