import type { SchemaGuardReport } from '../../../packages/auth-runtime/src/iam-account-management/schema-guard.ts';
import type { RuntimeProfile } from '../../../packages/core/src/runtime-profile.ts';
import type { AcceptanceDeployOptions, AcceptanceProbeResult, DoctorCheck, DoctorReport, RemoteRuntimeProfile } from '../runtime-env.shared.ts';
import type { RuntimeCommandRunnerDeps, RuntimeProfileInspectionDeps } from './runtime-deps.types.ts';

export type RuntimeRemoteCommandOrchestratorDeps = RuntimeCommandRunnerDeps & RuntimeProfileInspectionDeps & {
  acceptanceRemoteStateOps: ReturnType<typeof import('./acceptance-remote-state.ts').createAcceptanceRemoteStateOps>;
  applyCliOptionEnvOverrides: typeof import('./runtime-config.ts').applyCliOptionEnvOverrides;
  assertComposeServiceIngressLabels: typeof import('./deploy-project.ts').assertComposeServiceIngressLabels;
  assertComposeServiceNetworks: typeof import('./deploy-project.ts').assertComposeServiceNetworks;
  assertDangerousOperationApproved: typeof import('./runtime-approvals.ts').assertDangerousOperationApproved;
  assertDeterministicRemoteMutationContext: typeof import('../runtime-env.shared.ts').assertDeterministicRemoteMutationContext;
  assertRuntimeEnv: typeof import('./profile-env.ts').assertRuntimeEnv;
  buildAcceptanceReportPaths: typeof import('../runtime-env.shared.ts').buildAcceptanceReportPaths;
  buildGuardrailDoctorChecks: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['buildGuardrailDoctorChecks'];
  buildImagePlatformDoctorCheck: (env: NodeJS.ProcessEnv, options?: AcceptanceDeployOptions) => DoctorCheck;
  buildLocalProvisioningWorkerCheckBase: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['buildLocalProvisioningWorkerCheck'];
  buildProfileEnv: typeof import('./profile-env.ts').buildProfileEnv;
  buildProdParityProbePlan: typeof import('../runtime-env.shared.ts').buildProdParityProbePlan;
  buildQuantumDeployComposeDocument: typeof import('./deploy-project.ts').buildQuantumDeployComposeDocument;
  buildStudioImageVerifyEvidenceCheck: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['buildStudioImageVerifyEvidenceCheck'];
  buildTrustedForwardedHeaders: typeof import('../runtime-env.shared.ts').buildTrustedForwardedHeaders;
  checkHttpHealth: typeof import('./runtime-db.ts').checkHttpHealth;
  cliOptions: ReturnType<typeof import('../runtime-env.shared.ts').parseRuntimeCliOptions>;
  collectLocalInstanceIdentityDrift: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => readonly unknown[];
  commandExists: (commandName: string) => boolean;
  createDbSqlRunner: ReturnType<typeof import('./runtime-db.ts').createRuntimeDbOps>['createDbSqlRunner'];
  createStepResult: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['createStepResult'];
  decorateDoctorCheck: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['decorateDoctorCheck'];
  deployReportDir: string;
  doctorRuntime: (runtimeProfile: RuntimeProfile, env: NodeJS.ProcessEnv) => Promise<DoctorReport>;
  ensureDirs: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['ensureDirs'];
  finalizeDoctorReport: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['finalizeDoctorReport'];
  getConfiguredQuantumEndpoint: ReturnType<typeof import('./runtime-config.ts').createRuntimeConfigOps>['getConfiguredQuantumEndpoint'];
  getConfiguredStackName: ReturnType<typeof import('./runtime-config.ts').createRuntimeConfigOps>['getConfiguredStackName'];
  localWorkerStateFile: string;
  parseInstanceIdList: typeof import('./runtime-config.ts').parseInstanceIdList;
  parseJsonFromCommandOutput: typeof import('../runtime-env.shared.ts').parseJsonFromCommandOutput;
  parseRuntimeProfile: typeof import('../../../packages/core/src/runtime-profile.ts').parseRuntimeProfile;
  precheckAcceptance: (runtimeProfile: RemoteRuntimeProfile, env: NodeJS.ProcessEnv, options?: AcceptanceDeployOptions) => Promise<DoctorReport>;
  printDoctorReport: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['printDoctorReport'];
  printJsonIfRequested: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['printJsonIfRequested'];
  readLocalWorkerState: typeof import('./local-runtime.ts').readLocalWorkerState;
  resolveAcceptanceDeployOptions: typeof import('../runtime-env.shared.ts').resolveAcceptanceDeployOptions;
  resolveRemoteDangerousApprovalRequirement: typeof import('./runtime-approvals.ts').resolveRemoteDangerousApprovalRequirement;
  shouldCheckLocalInstanceRegistryDriftBeforeCommand: typeof import('./local-runtime.ts').shouldCheckLocalInstanceRegistryDriftBeforeCommand;
  shouldRunLocalProvisioningWorker: typeof import('./local-runtime.ts').shouldRunLocalProvisioningWorker;
  shouldSkipQuantumPrePull: ReturnType<typeof import('./runtime-config.ts').createRuntimeConfigOps>['shouldSkipQuantumPrePull'];
  sqlIdentifier: typeof import('./runtime-db.ts').sqlIdentifier;
  sqlLiteral: typeof import('./runtime-db.ts').sqlLiteral;
  summarizeProcessOutput: typeof import('./process.ts').summarizeProcessOutput;
  summarizeSchemaGuardFailures: typeof import('../../../packages/auth-runtime/src/iam-account-management/schema-guard.ts').summarizeSchemaGuardFailures;
  tenantSecretRegistryOps: ReturnType<typeof import('./tenant-secret-registry.ts').createTenantSecretRegistryOps>;
  toDoctorCheck: ReturnType<typeof import('./runtime-doctor-report.ts').createRuntimeDoctorReportOps>['toDoctorCheck'];
  validateRuntimeProfileEnv: typeof import('../../../packages/core/src/runtime-profile.ts').validateRuntimeProfileEnv;
  verifyDbSchemaSnapshot: typeof import('./runtime-db.ts').verifyDbSchemaSnapshot;
  verifyLocalDbSchemaSnapshot: ReturnType<typeof import('./runtime-db.ts').createRuntimeDbOps>['verifyLocalDbSchemaSnapshot'];
  wait: typeof import('./process.ts').wait;
  withoutDebugEnv: typeof import('./process.ts').withoutDebugEnv;
};
