export type RemoteEnvironment = 'dev' | 'staging' | 'prod';
export type RemoteConfigKind = 'config' | 'secret-value' | 'secret-reference';

type RemoteConfigKeyContract = Readonly<{
  kind: RemoteConfigKind;
  required?: boolean;
  type?: 'boolean' | 'integer' | 'url' | 'string';
}>;

const configKeys = [
  'APP_DB_USER', 'IAM_ADMIN_ENABLED', 'IAM_BULK_ENABLED', 'IAM_CSRF_ALLOWED_ORIGINS',
  'IAM_DEBUG_PROFILE_ERRORS', 'IAM_PII_ACTIVE_KEY_ID', 'IAM_UI_ENABLED',
  'KEYCLOAK_ADMIN_BASE_URL', 'KEYCLOAK_ADMIN_CLIENT_ID', 'KEYCLOAK_ADMIN_REALM',
  'KEYCLOAK_PROVISIONER_BASE_URL', 'KEYCLOAK_PROVISIONER_CLIENT_ID', 'KEYCLOAK_PROVISIONER_REALM',
  'POSTGRES_DB', 'POSTGRES_USER', 'SVA_ALLOWED_INSTANCE_IDS', 'SVA_AUTH_CLIENT_ID',
  'SVA_AUTH_DEBUG_HEADERS', 'SVA_AUTH_ISSUER', 'SVA_AUTH_POST_LOGOUT_REDIRECT_URI',
  'SVA_AUTH_REDIRECT_URI', 'SVA_ENABLE_SERVER_CONSOLE_LOGS', 'SVA_KEYCLOAK_PROVISIONER_POLL_INTERVAL_MS',
  'SVA_PARENT_DOMAIN', 'SVA_PUBLIC_BASE_URL', 'SVA_RUNTIME_PROFILE', 'SVA_STACK_NAME',
  'SVA_STUDIO_MCP_AUDIENCE', 'SVA_STUDIO_MCP_CLIENT_ID', 'SVA_STUDIO_MCP_ENABLED',
  'SVA_STUDIO_MCP_ISSUER', 'VITE_IAM_ADMIN_ENABLED', 'VITE_IAM_BULK_ENABLED', 'VITE_IAM_UI_ENABLED',
  'KEYCLOAK_OPERATOR_USER', 'OTEL_EXPORTER_OTLP_ENDPOINT', 'RESTORE_IAM_SMOKE_BASE_URL',
  'RESTORE_IAM_SMOKE_USERNAME', 'S3_BUCKET_PROD', 'S3_BUCKET_STAGING', 'S3_URL',
  'SVA_DEPLOY_REVISION', 'SVA_IMAGE_DIGEST', 'SVA_IMAGE_REF', 'SVA_IMAGE_TAG',
  'SVA_MAINSERVER_CLIENT_ID', 'SVA_MAINSERVER_GRAPHQL_URL', 'SVA_MAINSERVER_OAUTH_TOKEN_URL',
  'SVA_MONITORING_CONFIG_INIT_IMAGE_TAG', 'SVA_MONITORING_REGISTRY',
] as const;

const secretValueKeys = [
  'APP_DB_PASSWORD', 'ENCRYPTION_KEY', 'IAM_PII_KEYRING_JSON', 'KEYCLOAK_ADMIN_CLIENT_SECRET',
  'KEYCLOAK_PROVISIONER_CLIENT_SECRET', 'POSTGRES_PASSWORD', 'REDIS_PASSWORD',
  'SVA_AUTH_CLIENT_SECRET', 'SVA_AUTH_STATE_SECRET',
  'KEYCLOAK_OPERATOR_PASSWORD', 'RESTORE_IAM_SMOKE_PASSWORD', 'RESTORE_PROD_POSTGRES_PASSWORD',
  'RESTORE_PROD_SIGNING_KEY', 'RESTORE_STAGING_POSTGRES_PASSWORD', 'RESTORE_STAGING_SIGNING_KEY',
  'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY', 'SVA_MAINSERVER_CLIENT_SECRET',
] as const;

export const remoteConfigContract: Readonly<Record<string, RemoteConfigKeyContract>> = {
  ...Object.fromEntries(configKeys.map((key) => [key, { kind: 'config' as const }])),
  ...Object.fromEntries(secretValueKeys.map((key) => [key, { kind: 'secret-value' as const }])),
  WASTE_DATABASE_PROVISIONER_PASSWORD_SECRET_NAME: { kind: 'secret-reference', required: true },
  SVA_STUDIO_MCP_ENABLED: { kind: 'config', required: true, type: 'boolean' },
  SVA_KEYCLOAK_PROVISIONER_POLL_INTERVAL_MS: { kind: 'config', required: true, type: 'integer' },
  SVA_PUBLIC_BASE_URL: { kind: 'config', required: true, type: 'url' },
  SVA_AUTH_ISSUER: { kind: 'config', required: true, type: 'url' },
  SVA_AUTH_REDIRECT_URI: { kind: 'config', required: true, type: 'url' },
};

const requiredKeys = new Set([
  'APP_DB_PASSWORD', 'APP_DB_USER', 'ENCRYPTION_KEY', 'IAM_ADMIN_ENABLED', 'IAM_BULK_ENABLED',
  'IAM_CSRF_ALLOWED_ORIGINS', 'IAM_PII_ACTIVE_KEY_ID', 'IAM_PII_KEYRING_JSON', 'IAM_UI_ENABLED',
  'KEYCLOAK_ADMIN_BASE_URL', 'KEYCLOAK_ADMIN_CLIENT_ID', 'KEYCLOAK_ADMIN_CLIENT_SECRET',
  'KEYCLOAK_ADMIN_REALM', 'KEYCLOAK_PROVISIONER_BASE_URL', 'KEYCLOAK_PROVISIONER_CLIENT_ID',
  'KEYCLOAK_PROVISIONER_CLIENT_SECRET', 'KEYCLOAK_PROVISIONER_REALM', 'POSTGRES_DB', 'POSTGRES_PASSWORD',
  'POSTGRES_USER', 'REDIS_PASSWORD', 'SVA_ALLOWED_INSTANCE_IDS', 'SVA_AUTH_CLIENT_ID',
  'SVA_AUTH_CLIENT_SECRET', 'SVA_AUTH_ISSUER', 'SVA_AUTH_POST_LOGOUT_REDIRECT_URI',
  'SVA_AUTH_REDIRECT_URI', 'SVA_AUTH_STATE_SECRET', 'SVA_PARENT_DOMAIN', 'SVA_PUBLIC_BASE_URL',
  'SVA_RUNTIME_PROFILE', 'SVA_STACK_NAME', 'SVA_STUDIO_MCP_ENABLED',
]);

export const requiredRemoteConfigKeys = Object.entries(remoteConfigContract)
  .filter(([key, contract]) => contract.required || requiredKeys.has(key))
  .map(([key]) => key)
  .sort();
