export { callbackHandler, loginHandler, logoutHandler, meHandler } from './auth-route-handlers.js';
export { authorizeHandler } from './iam-authorization/authorize.js';
export { mePermissionsHandler } from './iam-authorization/me-permissions.js';

export {
  adminDataExportHandler,
  adminDataExportStatusHandler,
  assignGroupMembershipHandler,
  assignGroupRoleHandler,
  assignOrganizationMembershipHandler,
  bulkDeactivateUsersHandler,
  createContentHandler,
  createGroupHandler,
  createLegalTextHandler,
  createOrganizationHandler,
  createRoleHandler,
  createUserHandler,
  dataExportHandler,
  dataExportStatusHandler,
  dataSubjectMaintenanceHandler,
  dataSubjectRequestHandler,
  deactivateOrganizationHandler,
  deactivateUserHandler,
  deleteContentHandler,
  deleteGroupHandler,
  deleteLegalTextHandler,
  deleteRoleHandler,
  getContentHandler,
  getContentHistoryHandler,
  getGroupHandler,
  getMyDataSubjectRightsHandler,
  getMyOrganizationContextHandler,
  getMyProfileHandler,
  getOrganizationHandler,
  getUserHandler,
  getUserTimelineHandler,
  governanceComplianceExportHandler,
  governanceWorkflowHandler,
  instanceRegistryHandlers,
  legalHoldApplyHandler,
  legalHoldReleaseHandler,
  listAdminDataSubjectRightsCasesHandler,
  listContentsHandler,
  listGovernanceCasesHandler,
  listGroupsHandler,
  listLegalTextsHandler,
  listOrganizationsHandler,
  listPendingLegalTextsHandler,
  listPermissionsHandler,
  listRolesHandler,
  listUsersHandler,
  optionalProcessingExecuteHandler,
  profileCorrectionHandler,
  reconcileHandler,
  removeGroupMembershipHandler,
  removeGroupRoleHandler,
  removeOrganizationMembershipHandler,
  syncUsersFromKeycloakHandler,
  updateContentHandler,
  updateGroupHandler,
  updateLegalTextHandler,
  updateMyOrganizationContextHandler,
  updateMyProfileHandler,
  updateOrganizationHandler,
  updateRoleHandler,
  updateUserHandler,
} from '@sva/auth/server';
