export const dataRepositoriesVersion = '0.0.1';

export type DataRepositoriesPackageRole = 'postgres-repositories' | 'migration-adjacent-types' | 'server-data-access';

export const dataRepositoriesPackageRoles = [
  'postgres-repositories',
  'migration-adjacent-types',
  'server-data-access',
] as const satisfies readonly DataRepositoriesPackageRole[];

export {
  createIamSeedRepository,
  createInstanceIntegrationRepository,
  createInstanceRegistryRepository,
  createMediaRepository,
  createStudioJobRepository,
  createWasteDataSourceRepository,
  createWasteMasterDataRepository,
  iamSeedPlan,
  iamSeedStatements,
  instanceIntegrationStatements,
  mediaStatements,
  wasteDataSourceStatements,
  wasteMasterDataStatements,
} from './public-api.js';

export type {
  CachedInstanceIntegrationLoader,
  IamInstanceId,
  IamSeedPlan,
  IamSeedRepository,
  InstanceIntegrationRecord,
  InstanceIntegrationRepository,
  InstanceRegistryRepository,
  IntegrationProviderKey,
  MediaAssetListFilter,
  MediaAssetRecord,
  MediaReferenceRecord,
  MediaRepository,
  MediaStorageUsageRecord,
  MediaStorageQuotaCheck,
  MediaStorageQuotaRecord,
  StudioJobRepository,
  MediaUploadSessionRecord,
  MediaUsageImpact,
  MediaVariantRecord,
  PermissionKey,
  PersonaSeed,
  StudioJobListResult,
  StudioJobListResultItem,
  SqlExecutionResult,
  SqlExecutor,
  SqlPrimitive,
  SqlStatement,
  WasteDataSourceRepository,
  WasteMasterDataRepository,
} from './public-api.js';

export type {
  WasteCollectionLocationListFilter,
  WasteCollectionLocationRecord,
  InstanceAuditEvent,
  InstanceProvisioningRun,
  InstanceRegistryRecord,
  WasteCustomTourDate,
  WasteCityListFilter,
  WasteCityRecord,
  WasteFractionListFilter,
  WasteFractionRecord,
  WasteGlobalDateShiftListFilter,
  WasteGlobalDateShiftRecord,
  WasteHouseNumberListFilter,
  WasteHouseNumberRecord,
  WasteLocationTourLinkListFilter,
  WasteLocationTourLinkRecord,
  WasteRegionListFilter,
  WasteRegionRecord,
  WasteStreetListFilter,
  WasteStreetRecord,
  WasteTourDateShiftListFilter,
  WasteTourDateShiftRecord,
  WasteTourListFilter,
  WasteTourRecurrence,
  WasteTourRecord,
} from '@sva/core';
