export const pluginSdkVersion = '0.0.1';

export type PluginSdkPackageRole =
  | 'plugin-contracts'
  | 'plugin-platform'
  | 'admin-resources'
  | 'content-types'
  | 'plugin-i18n';

export const pluginSdkPackageRoles = [
  'plugin-contracts',
  'plugin-platform',
  'admin-resources',
  'content-types',
  'plugin-i18n',
] as const satisfies readonly PluginSdkPackageRole[];

export type {
  AdminResourceDefinition,
  AdminResourceBulkActionSelectionMode,
  AdminResourceCapabilities,
  AdminResourceDetailCapabilities,
  AdminResourceGuard,
  AdminResourceListBulkActionCapability,
  AdminResourceListCapabilities,
  AdminResourceListFilterCapability,
  AdminResourceListFilterOption,
  AdminResourceListPaginationCapability,
  AdminResourceListSearchCapability,
  AdminResourceListSortingCapability,
  AdminResourceViewDefinition,
  AdminResourceViews,
  BuildTimeRegistry,
  BuildTimeRegistryInput,
  ContentTypeActionDefinition,
  ContentTypeDefinition,
  ContentTypeEditorFieldDefinition,
  ContentTypeEditorFieldKind,
  ContentTypeListColumnDefinition,
  HostMediaFieldOption,
  HostMediaAssetListItem,
  HostMediaReferenceSelection,
  MainserverCrudClientOptions,
  MainserverErrorFactory,
  MainserverListQuery,
  PluginActionDefinition,
  PluginActionRegistryEntry,
  PluginAdminResourceDefinition,
  PluginAuditEventDefinition,
  PluginAuditEventRegistryEntry,
  PluginDefinition,
  PluginCatalogEntry,
  PluginCatalogIssue,
  PluginCatalogIssueCode,
  PluginCatalogIssueSeverity,
  PluginCatalogSourceType,
  PluginExecutionAuditReporter,
  PluginExecutionBaseContext,
  PluginExecutionContextCapabilities,
  PluginExecutionLogger,
  PluginExecutionProgressReporter,
  PluginIntegrationExecutionContext,
  PluginJobExecutionHandler,
  PluginJobExecutionResult,
  PluginJobHandlerContext,
  PluginImportProfileDefinition,
  PluginImportProfileRegistryEntry,
  PluginImportProfileValidationMode,
  PluginJobExecutionContext,
  PluginJobProgressReporter,
  PluginJobTypeDefinition,
  PluginJobTypeRegistryEntry,
  PluginManifest,
  PluginManifestCapability,
  PluginPlatformHost,
  PluginModuleIamContract,
  PluginModuleIamRegistryEntry,
  PluginModuleIamSystemRoleDefinition,
  PluginPermissionDefinition,
  PluginPermissionRegistryEntry,
  PluginGuardrailViolationCode,
  PluginGuardrailViolationInput,
  PluginNavigationItem,
  PluginNavigationSection,
  PluginRouteDefinition,
  PluginRouteGuard,
  PluginRequestExecutionContext,
  PluginSnapshot,
  ResolvedPluginCatalog,
  StandardContentAdminResourceOptions,
  StandardContentPluginActionIds,
  StandardContentPluginActionName,
  StandardContentPluginActionOptions,
  StandardContentPluginContributionOptions,
  PluginTranslations,
  PluginTranslationResolver,
  PluginTranslationVariables,
  RouteFactory,
  MediaPickerDefinition,
  MediaPickerSelectionMode,
} from './public-api.js';

export {
  createAdminResourceRegistry,
  createBuildTimeRegistry,
  assertPluginContributionAllowedKeys,
  assertPluginRoutePathAllowed,
  createContentTypeRegistry,
  createPluginContributionGuardrailError,
  createPluginGuardrailError,
  createPluginActionRegistry,
  createPluginAuditEventRegistry,
  createPluginSnapshot,
  createPluginImportProfileRegistry,
  createPluginJobTypeRegistry,
  createPluginModuleIamRegistry,
  createPluginPermissionRegistry,
  createPluginRegistry,
  resolvePluginCatalog,
  createStandardContentAdminResource,
  createStandardContentModuleIamContract,
  createStandardContentPluginActionIds,
  createStandardContentPluginActions,
  createStandardContentPluginContribution,
  createStandardContentPluginPermissions,
  createStandardContentPluginSystemRoles,
  createStandardContentTypeDefinition,
  createMainserverCrudClient,
  createMainserverJsonRequestHeaders,
  buildMainserverListUrl,
  definePluginActions,
  definePluginCatalogEntry,
  definePluginAdminResources,
  definePluginAuditEvents,
  definePluginExecutionContextCapabilities,
  definePluginImportProfiles,
  definePluginJobTypes,
  definePluginManifest,
  defineMediaPickerDefinition,
  compactOptionalString,
  findHostMediaReferenceAssetId,
  fromDatetimeLocalValue,
  listHostMediaAssets,
  listHostMediaReferencesByTarget,
  replaceHostMediaReferences,
  definePluginModuleIamContract,
  definePluginPermissions,
  definePluginContentTypes,
  genericContentTypeDefinition,
  getContentTypeDefinition,
  MainserverApiError,
  mergeAdminResourceDefinitions,
  mergePluginActions,
  mergePluginAdminResourceDefinitions,
  mergePluginAuditEventDefinitions,
  mergePluginContentTypes,
  mergePluginImportProfiles,
  mergePluginJobTypes,
  mergePluginModuleIamContracts,
  mergePluginNavigationItems,
  mergePluginPermissions,
  mergePluginRouteDefinitions,
  mergePluginTranslations,
  pluginGuardrailViolationCodes,
  registerPluginTranslationResolver,
  requestMainserverJson,
  toDatetimeLocalValue,
  toHostMediaFieldOptions,
  translatePluginKey,
  usePluginTranslation,
} from './public-api.js';
