import type { MediaRepository } from '@sva/data-repositories';

export const createMediaService = (repository: MediaRepository) => ({
  listAssets: repository.listAssets,
  countAssets: repository.countAssets,
  getAssetById: repository.getAssetById,
  getAssetByStorageKey: repository.getAssetByStorageKey,
  getProvisionalAssetByDraft: repository.getProvisionalAssetByDraft,
  listAssetsByOperation: repository.listAssetsByOperation,
  deleteAsset: repository.deleteAsset,
  deleteVariantsByAssetId: repository.deleteVariantsByAssetId,
  upsertAsset: repository.upsertAsset,
  upsertVariant: repository.upsertVariant,
  listVariantsByAssetId: repository.listVariantsByAssetId,
  upsertUploadSession: repository.upsertUploadSession,
  getUploadSessionById: repository.getUploadSessionById,
  getUploadSessionByAssetId: repository.getUploadSessionByAssetId,
  claimUploadSession: repository.claimUploadSession,
  lockUploadSessionClaim: repository.lockUploadSessionClaim,
  upsertStorageUsage: repository.upsertStorageUsage,
  applyStorageUsageDelta: repository.applyStorageUsageDelta,
  tryApplyStorageUsageWithinQuota: repository.tryApplyStorageUsageWithinQuota,
  getStorageUsage: repository.getStorageUsage,
  upsertStorageQuota: repository.upsertStorageQuota,
  getStorageQuota: repository.getStorageQuota,
  wouldExceedStorageQuota: repository.wouldExceedStorageQuota,
  replaceReferences: repository.replaceReferences,
  listReferencesByAssetId: repository.listReferencesByAssetId,
  listReferencesByTarget: repository.listReferencesByTarget,
  getUsageImpact: repository.getUsageImpact,
  createContentSaveOperation: repository.createContentSaveOperation,
  getContentSaveOperation: repository.getContentSaveOperation,
  replaceContentSaveOperationReferences: repository.replaceContentSaveOperationReferences,
  markContentSaveOperationContentSaved: repository.markContentSaveOperationContentSaved,
  markContentSaveOperationSavingContent: repository.markContentSaveOperationSavingContent,
  markContentSaveOperationOutcomeUnknown: repository.markContentSaveOperationOutcomeUnknown,
  commitContentSaveOperation: repository.commitContentSaveOperation,
  markContentSaveOperationAbandonPending: repository.markContentSaveOperationAbandonPending,
  finalizeContentSaveOperationAbandoned: repository.finalizeContentSaveOperationAbandoned,
  claimContentSaveOperationRecovery: repository.claimContentSaveOperationRecovery,
  finalizeContentSaveOperationCleanup: repository.finalizeContentSaveOperationCleanup,
});

export type MediaService = ReturnType<typeof createMediaService>;
