name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: ./.github/actions/setup-pnpm-workspace
        with:
          nx-cloud-encryption-key: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx affected -t lint test build
      - run: pnpm exec nx fix-ci
        if: always()
