name: Main Build

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: App Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: ./.github/actions/setup-pnpm-workspace
      - run: pnpm nx run sva-studio-react:build
